mainsail-crew/mainsail

README.md

Your terminal commands are for the latest update V0.0.12, but the header text still said V0.0.11 🙂
Idk why it says I replaced the last line... it didn't change 😕 
Btw, this is amazing work! 👏

Bumped Update Header Text to current version

---

public/index.html
src/store/actions.js

Note: package-lock.json still has kwc in the name. I didn't change due to it being build-related

Renaming kwc to mainsail

---

src/components/panels/Settings/LimitsPanel.vue

Current headline is written as Machinelimits
Changed to Machine Limits

Machine Limits Typo

---

src/components/panels/ExtruderPanel.vue

Removes the unnecessary M120 and M121 g-codes when sending an extrude or retract command via the Extrude/Retract button via the Dashboard, which would lead to an "unknown command" error message in the Mainsail console.

bugfix: remove M120/M121 from extrude/retract command

---

src/pages/Files.vue

Moonraker expects file paths to use un-escaped file paths,
such as gcodes/some%20file.gcode, but encodeURIComponent
will always escape the slash. Using encodeURI here will not.

Use encodeURI for paths

---

.gitignore
src/components/panels/Settings/WebcamPanel.vue
src/components/panels/WebcamPanel.vue
src/pages/Webcam.vue
src/store/getters.js
src/store/index.js

- Adds settings to toggle a flip on the X or Y axis of the webcam image.
- Updates the webcam view to apply the above two transforms based on the settings.
- Updates default config to represent both toggles off.
- Moves the webcam URL to the same location as other webcam configuration.
- Added a base `.gitignore` to avoid accidental commits to things like `node_modules`.
@meteyou I wasn't sure what your intent was with the webcam URL, so I moved it to be consistent. Happy to move this back if you feel that's appropriate tho.
Also - I've left the settings in place to allow rotation of the webcam feed, but have hidden the controls for now. Allowing rotation on an image that is not square causes issues, as rotation happens after page layout. I researched a bunch of ways to reposition layout …

feature: allows flipping the webcam horizontally and vertically

---

src/pages/Console.vue

This stops chrome from breaking the cnonsole history feature

Disable browser autocomplete in console

---

src/components/panels/Settings/ConfigFilesPanel.vue
src/components/panels/Settings/SystemPanel.vue
src/main.js
src/pages/Files.vue
src/store/actions.js

I like to run all my web services proxied through a single
internet-accessible server, secured through SSL and authenticated
against a single proxy server (nginx, in my case)
I found that mainsail hardcoded ws:// and many http:// addresses, so
I've updated them to detect ws:// vs ws:///, and just use the protocol
agnostic // prefix, which then sends the request over the same protocol
the page is loaded under, either http or https.
Now i've got a nice SSL secured but publicly accessible URL for remote
printer monitoring

Support mainsail through an SSL proxy

---

docs/installation.md

Old Pull Request: https://github.com/meteyou/mainsail/pull/78
Revised to place config in `/etc/nginx/sites-available/mainsail`
Also modified `gzip_comp_level` to a value of `4` instead of the default `6` to lower CPU usage... it _may_ now work on the PI Zero without killing the CPU, but I don't have one to test with.

Enhancement: Add enabling Gzip for mainsail nginx config

---

docs/installation.md

- Moves the upstream and common vars to separate configuration files. This means other clients can make use of the same upstreams, on the same machine - without conflicts. Matches MainsailOS's configuration.

refactor: docs move upstreams and common vars to independent conf

---

src/store/mutations.js

Moonraker changed gcode_store to no longer return a string:
https://github.com/Arksine/moonraker/commit/2d77400a651b147b0c97feb016000c12d67a1427

handle gcode_store data format changes from moonraker

---

src/store/mutations.js

Moonraker changed the modified date to a unix timestamp:
October 21st, 2020
https://github.com/Arksine/moonraker/commit/dfb1e199480faa2836305ddbcf625b0d1fc1c582
https://github.com/Arksine/moonraker/commit/f2fb8d33d4c07c9ca7b1341422f28ae7be7d5169

Modified times now come as unix times

---

src/pages/Files.vue

If you upload a file, then delete it, and then upload the same one with the upload button, it will not upload it. This is because it has the same name and the input type="file" does not trigger a change.
This might not be a problem across all browsers and for those that have this problem, this might not fix them all. This way is the "easy" workaround. The other way is to either completely replace the DOM element, or wrap it inside a form and "reset" that form. If this continues to be an issue, we can investigate those other methods.
This *may* resolve:
https://github.com/meteyou/mainsail/issues/90

clear fileupload after uploading

---

docs/setup-guide/manual-setup/mainsail.md

Simplifying nginx config in manual setup documentation by replacing multiply locations entry with regex one.

Just simplifying nginx config in manual setup documentation

---

src/components/panels/WebcamPanel.vue

Computers with agressive power management policies tend to stop the webcam feed after getting to sleep.
This forces the webcam feed to be restarted on focus.

feat(refresh-webcam): Refresh webcam panel on focus

---

src/components/panels/StatusPanel.vue

I was doing some digging to see if I could drop the CPU utilization of Mainsail some, and I spotted (I think in one of the Vue inspector panes) that the result of the percentage the circular progress bar winds up calculating to some _extremely_ precise number, which causes the progress circle to refresh... well, a _lot_:
https://user-images.githubusercontent.com/2745/105616300-91a8b980-5d9b-11eb-8e91-c80ba4ecc4b3.mov
I changed it to round to whatever the closest percentage is, and it's _much_ more calm:
https://user-images.githubusercontent.com/2745/105616463-ab96cc00-5d9c-11eb-8ac2-0096f5cd5cc8.mov
Anecdotally, doing so seems to drop the CPU utilization by about 10-20%, depending on the browser 🎉

Drop update rate on progress circle for significantly less CPU utilization

---

docs/_config.yml

I accidentally removed the logo from the config during the recent commit.

hotfix: mainsail docs logo

---

package.json
src/components/panels/Settings/WebcamPanel.vue
src/components/panels/WebcamPanel.vue
src/main.js

As some of you may know, with the native MJPEG Streaming implementation *every* frame is sent from the server to the client. This can cause a slow-down (and subsequent speed-up) phenomenon for the client, if the bandwidth is not sufficient. Sometimes causing the stream being seen to be 2 minutes in the past.
Therefore I've implemented a pull-based method for frames, where the client only requests a new frame once the previous one has finished loading. With a bit of a limiter and smoothing put in place to hit a desired target fps, **very** heavily inspired by [PyImageStream](https://github.com/Bronkoknorb/PyImageStream), which I've tried out previously but noticed a very high CPU usage (~60% load on a Pi3 😬) --- probably due to its pygame dependency for frame grabbing, which is known to be …

MJPEG-Streamer Adaptive FPS / Frame Skipping

---

docs/quicktips/presets.md

Specified that gcode is executed after the temperatures are set.
Solves #196

Added info about presets gcode

---

docs/necessary-cfg.md

add home and temperature check to the default macros. This will avoid errors if PAUSE or RESUME is executed while not homed or extruder below minimum temperature.
Signed-off-by: Alex Zellner alexander.zellner@googlemail.com

docs: add home and temp check to PAUSE and RESUME

---

src/components/panels/KlipperWarningsPanel.vue
src/components/panels/MoonrakerStatePanel.vue
src/components/panels/StatusPanel.vue
src/locales/en.json

klipper pr for warnings: https://github.com/KevinOConnor/klipper/pull/4659

feature: add klipper warnings panel on the dashboard

---

src/store/server/getters.ts

when not running on pi this should be checked for null, because of which the System Panel is prevented being loaded.

fix: check for null when running in docker or non pi

---

src/store/printer/getters.ts

when using sensor names like this
```
[temperature_sensor HAL]
sensor_type: temperature_host
sensor_path: /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp3_input
```
it was causing the SystemLoads panel to break, mostly because they keys were being looked up were all lowercase. This correctly looks up the keys.

fix: allow upper case sensor names

---

src/plugins/helpers.ts

Fix macro param regexp

---

src/store/getters.ts

resolves an issue where the dependency panel pops up for a fraction of a second and falsely displays an outdated moonraker version detected on the users system.

fix: bug in dependency getter

---

src/store/farm/printer/index.ts

fix: support for printer farm in https mode

---

src/components/inputs/FirmwareRetractionSettingsInput.vue
src/components/inputs/MotionSettingsInput.vue
src/components/inputs/PressureAdvanceSettingsInput.vue
src/components/panels/MachineSettings/FirmwareRetractionSettings.vue
src/components/panels/MachineSettings/MachineSettingsPanel.vue
src/components/panels/MachineSettings/MotionSettings.vue
src/components/panels/MachineSettings/PressureAdvanceSettings.vue
src/components/panels/PressureAdvanceSettings.vue
src/components/panels/PrintsettingsPanel.vue
src/locales/de.json
src/locales/en.json

feat: pressure advance settings on dashboard

---

src/components/panels/MachineSettings/MotionSettings.vue
src/locales/de.json
src/locales/en.json

fix: correct spelling of `max_accel_to_decel` input field (fixes #474)

---

src/components/mixins/base.ts

It can occur, that a browser on Windows 10 reports a maxTouchPoints count of 256, even though it is a desktop system without any touch functionality at all. See also: https://stackoverflow.com/a/67909182
Short codepen snippet to report maxTouchPoints count with an alert gave: 

fix: ignore maxTouchPoints === 256

---

src/store/gui/actions.ts

Previously, data was stored in an outdated store.
Updating to the correct keyName to use the correct store.

fix: dispatch with correct keyName

---

src/components/gcodeviewer/Viewer.vue

buttons and inputs got squished together on small screens
fixed by re-ordering and allowing wrapping of display columns of the gcode viewer menu

fix: button and input placement in gcode viewer

---

src/components/gcodeviewer/Viewer.vue

* leave zSlider enabled when start tracking current file
* set zSlider to max on start tracking
* disable tracking when pressing the clear button

Fix: zSlider and clear button in gcodeviewer

---

src/components/panels/ControlPanelCrossControl.vue
src/components/settings/SettingsControlTab.vue
src/locales/de.json
src/locales/en.json

new move distance values only were usable, after cross styled control where re-rendered from page reload or change
* added key to button toggle group from which the move distance is selected

Fix: control panel cross style

---

src/components/panels/ControlPanelExtruder.vue

`min_extrude_temp` is undefined if the user has not specified `min_extrude_temp` in their Klipper config leading to a small display error in the extrude/retract tooltip:
This PR sets `min_extrude_temp`to Klipper's default 170 if it is undefined.
Signed-off-by: Morten Lindhardt <r3fuze@gmail.com>

fix: set default for min_extrude_temp

---

src/components/panels/GcodefilesPanel.vue
src/components/panels/HistoryListPanel.vue
src/components/panels/Machine/ConfigFilesPanel.vue
src/components/panels/StatusPanel.vue
src/components/panels/Timelapse/TimelapseFilesPanel.vue

GET requests including file names with special characters such as '%' will properly encode the request to the server.
I run mainsail and moonraker behind Nginx. My g-code files are named to include infill percentage, i.e. "25%", which for URLs is a reserved escape character. Nginx parses these requests incorrectly and returns a 400 Bad Request code, leaving thumbnail icons and timelapse videos inaccessible for me.
Clicking the first file in timelapse view breaks:
Note the g-code file without the '%' symbol successfully obtains it's thumbnail, but all others are breaking.
I did a grep through the code base and replaced lines where encodeURI was missing for the GET request.
The first timelapse video is successfully found and displayed:
Lmk about any concerns, and thank you for providing a …

fix: encodeURI for thumbnails and timelapse files

---

docker/Dockerfile

The npm docker image is using `node:buster` as base image, and that currently points to Node 17 (current, not LTS)
Node 17 introduced a new OpenSSL provider and some dependencies do not work with it (though one can set `NODE_OPTIONS` to `--openssl-legacy-provider` in order to use the legacy provider)
As the existing workflow is using Node 16, the easiest fix is to just point the base image to Node 16, hence this fix.
Fixes #567
Signed-off-by: Pedro Lamas <pedrolamas@gmail.com>

chore: Use node 16 for base docker image

---

package.json

If one tries to build Mainsail with the latest Node (17 at the time of writing), it will not work as it has a new OpenSSL provider that is not directly compatible with some of the dependencies (though one can set `NODE_OPTIONS` to `--openssl-legacy-provider` in order to use the legacy provider)
In any case, as the current workflow is using Node 16 (LTS at time of writing), I think it would be wise to fix that version so anyone trying to build from source gets a warning if they are using a different version of Node.
Signed-off-by: Pedro Lamas <pedrolamas@gmail.com>

chore(build): Sets Node engine to version 16

---

src/components/panels/Timelapse/TimelapseFilesPanel.vue

When using mainsail on a different port, the video preview and download link was pointing to a wrong url.
Signed-off-by:  Christoph Frei <fryakatkop@gmail.com>

fix: video and download link in timelapse video dialog

---

docker/config/moonraker.conf.example

I couldn't start the development environment initially using Docker. 
Got this error:
```
PermissionError: [Errno 13] Permission denied: '/root/.moonraker_database'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/node/moonraker/moonraker/moonraker.py", line 872, in main
server = Server(app_args, file_logger, event_loop)
File "/home/node/moonraker/moonraker/moonraker.py", line 152, in __init__
self._load_components(config)
File "/home/node/moonraker/moonraker/moonraker.py", line 230, in _load_components
self.load_component(config, component)
File "/home/node/moonraker/moonraker/moonraker.py", line 257, in load_component
raise ServerError(msg)
utils.ServerError: Unable to load component: (database)
2022-01-28 14:14:43,035 …
```

chore: fix initial development environment

---

.github/workflows/build_size_report.yml

The hashes are 8 characters instead of 5.﻿

ci: fix incorrect hash length of the bundle report

---

src/plugins/longpress.ts

Migrated the last js file to ts﻿.

refactor: migrate `longpress.js` to `longpress.ts`

---

src/store/socket/index.ts

This fixes the problem described in https://github.com/mainsail-crew/mainsail/pull/594#pullrequestreview-880965010.
>For me, Mainsail has been trying to connect to moonraker on port 0 (rather than port 80) ever since this PR has been merged. The issue is that in the case Mainsail falls back onto window.port.location, if the browser has loaded mainsail via HTTP on port 80, said variable will be an empty string (as per [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Location/port)). Number('') yields 0, which makes Mainsail connect on the wrong port. Removing the cast to number fixes the issue.

refactor: make sure that port '80' and '443' are correctly passed through

---

src/components/inputs/NumberInput.vue

This PR will add a new, custom number input component which is meant to be as re-usable as possible throughout the whole project.
With this component added, we will be able to completely replace:
https://github.com/mainsail-crew/mainsail/blob/develop/src/components/inputs/FirmwareRetractionSettingsInput.vue
https://github.com/mainsail-crew/mainsail/blob/develop/src/components/inputs/MotionSettingsInput.vue
https://github.com/mainsail-crew/mainsail/blob/develop/src/components/inputs/PressureAdvanceSettingsInput.vue
as those files currently hold a lot of duplicated code.

feat: add custom number input component

---

.github/workflows/build_size_report.yml
.github/workflows/code_style.yml

The size report is only ran after adding the label. This way `pull_request_target` is still safe to use.
Like this:
If you want something different than `analyze`, just let me know.
Also updated the linter jobs to be a bit more standard.

ci: run build size report on 'analyze' label

---

.github/workflows/build_size_report.yml

This makes sure the PR gets run instead of upstream.

ci: use the correct sha for the compressed size action check

---

src/components/TheEditor.vue
src/components/inputs/CodemirrorAsync.ts

This loads codemirror into a seperate chuk for faster LCP.
More information: https://web.dev/lcp/
You can use the `analyze` label to see the difference in bundle size.

perf: load codemirror into a chunk for faster LCP

---

.github/workflows/build_size_report.yml

This way we can compare the total size of the mainsail dist package﻿

ci: add more filetypes to the bundle size check

---

vite.config.ts

allows connecting to the local development server with all devices on the same network, making it possible to connect with mobile devices for testing etc.

chore: add host settings to vite.config.ts

---

src/components/panels/MiniconsolePanel.vue
src/pages/Console.vue
src/store/actions.ts
src/store/gui/console/actions.ts
src/store/gui/console/getters.ts
src/store/gui/console/mutations.ts
src/store/gui/console/types.ts
src/store/server/actions.ts
src/store/server/getters.ts
src/store/server/mutations.ts
src/store/server/types.ts

This just keeps a `cleared_since` date in the database and filters the events that came before that.

feat(console): add the ability to clear the console

---

.docker/nginx.conf
.github/workflows/publish_docker.yml
Dockerfile

This creates an official image for Mainsail that can be used by Docker users.﻿
How to test this:
```sh
docker build . -t mainsail && docker run -p "4444:80" mainsail
```
Open http://localhost:4444

build: add official Docker image

---

src/components/TheSelectPrinterDialog.vue
src/locales/en.json

fix: don't allow to add/update printers with empty hostname

---

src/App.vue
src/components/TheSelectPrinterDialog.vue
src/components/mixins/base.ts
src/components/settings/SettingsRemotePrintersTab.vue
src/main.ts
src/store/actions.ts
src/store/gui/actions.ts
src/store/gui/remoteprinters/actions.ts
src/store/index.ts
src/store/mutations.ts
src/store/socket/actions.ts
src/store/socket/index.ts
src/store/socket/types.ts
src/store/types.ts

this PR will fix #630 
config.json example:
```json
{
"remoteMode": true,
"instances": [
{ "hostname": "192.168.0.210", "port": 7125 },
{ "hostname": "192.168.0.211", "port": 7125 }
]
}
```

feat: add default moonraker instances to config.json

---

src/components/settings/SettingsEditorTab.vue
src/locales/de.json
src/locales/en.json
src/store/editor/actions.ts
src/store/editor/getters.ts
src/store/gui/index.ts
src/store/gui/types.ts

switch between 'FIRMWARE_RESTART' and 'FIRMWARE' for klipper or add an option to select the right moonraker instance in multi instance systems.

feat: add settings for klipper & moonraker 'SAVE & RESTART'

---

src/store/server/actions.ts
src/store/server/mutations.ts
src/store/socket/index.ts
src/store/socket/types.ts
src/store/variables.ts

send an identification if websocket is connected.
moonraker.log looks like this after this PR:
```
2022-03-05 23:12:34,650 [websockets.py:open()] - Websocket Opened: ID: 1740547184, Proxied: True, User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36, Host Name: 192.168.0.212
2022-03-05 23:12:35,098 [websockets.py:_handle_identify()] - Websocket 1740547184 Client Identified - Name: mainsail, Version: 2.2.0-alpha, Type: web
```

feat: implement moonraker connection identify

---

src/components/panels/FarmPrinterPanel.vue

fix: hide gcode thumbnail, if a webcam is active in printer farm

---

.editorconfig

style: indent size of 4 spaces in json

---

src/components/gcodeviewer/Viewer.vue
src/routes/index.ts
src/store/gui/actions.ts
src/store/gui/index.ts
src/store/gui/types.ts
src/store/printer/actions.ts

feat: display gcodeviewer always and store klipper settings in moonraker DB as a fallback

---

src/components/panels/GcodefilesPanel.vue

The mdi icon which is displayed for gcode files without embedded thumbnails was missing due to a missing import of that icon, resulting in an error in the browser console.

fix: missing file icon import in gcode file browser

---

src/components/panels/WebcamPanel.vue
src/locales/de.json
src/locales/en.json

fix: add error message in webcam panel, if no webcam is available

---

src/locales/de.json
src/locales/en.json
src/locales/hu.json
src/locales/it.json
src/locales/nl.json
src/locales/pl.json
src/locales/ru.json
src/locales/zh-tw.json
src/locales/zh.json

style: fix lint issue of locale files

---

src/components/panels/HistoryListPanel.vue
src/components/panels/Machine/ConfigFilesPanel.vue

change delete button color from warning to error in:
* config files panel
* print history
* print history context menu

refactor: change delete button color

---

src/components/panels/Machine/ConfigFilesPanel.vue

Fixes the delete button color for deleting folders in the config file filemanager

fix(ConfigFilesPanel): change delete button color

---

src/App.vue
src/assets/styles/toastr.css
src/assets/styles/utils.scss
src/components/TheFullscreenUpload.vue
src/components/TheUploadSnackbar.vue
src/components/panels/GcodefilesPanel.vue
src/components/panels/Machine/ConfigFilesPanel.vue
src/locales/de.json
src/locales/en.json
src/store/files/actions.ts
src/store/files/index.ts
src/store/files/mutations.ts
src/store/files/types.ts
src/store/gui/index.ts
src/store/gui/types.ts

feat: global fullscreen fileupload

---

src/components/panels/TemperaturePanel.vue

fix: margin bottom of TemperaturePanel.vue

---

src/components/panels/ToolheadControls/MoveToControl.vue
src/components/panels/ToolheadControls/ZoffsetControl.vue
src/locales/en.json
src/store/printer/getters.ts
src/store/variables.ts

chore: some toolhead panel tweaks

---

src/components/panels/MachineSettings/FirmwareRetractionSettings.vue
src/components/panels/MachineSettings/MachineSettingsPanel.vue
src/components/panels/MachineSettings/MotionSettings.vue
src/locales/de.json
src/locales/en.json

- MachineSettingsPanel.vue: change header to "Machine" only
- MachineSettingsPanel.vue: remove sub panel from motion settings if no firmware retraction is enabled
- MachineSettingsPanel.vue: use custom breakpoints instead of vuetify classes for finer breakpoint control
- MotionSettings.vue: replace v-card-text wrapper with v-container
- FirmwareRetractionSettings.vue: replace v-card-text wrapper with v-container

refactor(MachineSettingsPanel.vue): tweak visual appearance

---

.github/workflows/publish_docker.yml

Added arm64 image support to publish_docker.yml workflow file.
I have built and tested this workflow on my branch. Unfortunately, I could not get armv7 support to work. It seems that cypress does not support arm 32 bit. https://github.com/cypress-io/cypress/issues/4478 For my purposes I only needed an arm64 image.

feat: add arm64 docker image support

---

src/components/panels/JobqueuePanel.vue
src/components/panels/Status/Jobqueue.vue
src/locales/de.json
src/locales/en.json

fix: add missing context menu to dashboard jobqueue

---

src/components/charts/TempChart.vue
src/store/printer/tempHistory/actions.ts

This should fix https://github.com/mainsail-crew/mainsail/issues/799
There was, what i assume, an issue during the construction of the dataset for the tempchart which led to duplicated pushes of the pwm fan name.
Lets say i had a pwm fan with the name `my_pwm_fan`, a dataset for `my_pwm_fan` and a dataset for `my_pwm_fan-speed` was added to the master dataset resulting in duplicated entries for the pwm checkbox and duplicated entries for the tempchart tooltip.

fix: duplicate checkbox for pwm fan (fixes #799)

---

src/components/panels/ToolheadControlPanel.vue

fix: disable toolhead 3-dot menu during printing (fixes #812)

---

src/components/panels/TemperaturePanel.vue
src/store/printer/getters.ts
src/store/printer/types.ts

This PR will correct an issue with the `PrinterStateTemperatureObject` interface.
`object.rpm` in `TemperaturePanel.vue` always returned a string because `RPM` got appended to the rpm value, which made a checking for `!== null` always be true.

fix: do not show `null RPM` in temp chart (fixes #818)

---

src/components/settings/SettingsControlTab.vue

This PR fixes an issue with a duplicated extruder settings header and removes it.
It also improves the visuals of said headers by adding their respective panel icons and a divider to the header.

refactor: remove duplicated settings header

---

src/components/webcams/Mjpegstreamer.vue

fix: don't createObjectURL, when webcam img doesn't exist in Mjpegstreamer.vue

---

src/components/notifications/NotificationMenuEntry.vue

fix: regex to replace url to a clickable link in notifictiaons

---

src/components/webcams/Mjpegstreamer.vue
src/components/webcams/MjpegstreamerAdaptive.vue
src/components/webcams/Uv4lMjpeg.vue
src/main.ts

fix: stop webcam when webcam panel is collapse

---

src/store/gui/actions.ts

fix: wrong default path in moonraker db

---

src/components/panels/ExtruderControlPanel.vue
src/store/printer/getters.ts
src/store/printer/types.ts

This will require the user to set up dedicated tool change macros in the form of `T0`, `T1` ... `Tn` to be able to switch between them via Mainsail. Not having those macros defined, will make those buttons NOT appear anymore.
This implementation lacks the highlighting of the currently active tool in case of multiple extruder that are set up with `extruder_stepper` and are being synced to a motion queue due to technical limitations of Klipper (it currently seems to be impossible to detect which extruder_stepper is currently synced to the active extruder). Highlighting the current active extruder in regular multi extruder setups is still functional!

fix: tool selection in extruder panel

---

src/components/mixins/dashboard.ts
src/pages/Dashboard.vue
src/store/gui/getters.ts
src/store/printer/getters.ts

- hide toolhead panel, if kinematics === none
- hide extruder panel, if no extruder is in the config
- hide temperature panel, if header & sensor count === 0

fix: hide toolhead, extruder & temperature panel if they have no content

---

src/pages/Heightmap.vue

On mobile, the correct method for opening the naming dialog for the new bed mesh wasn't called.

fix: bed mesh calibrate dialog not opening on mobile

---

src/components/panels/ExtruderControlPanel.vue
src/store/printer/getters.ts
src/store/printer/types.ts

This PR is (hopefully only) a temporary solution to this issue: https://github.com/mainsail-crew/mainsail/issues/845
There is no safe way to set pressure advance values via those input fields, so we now disable them once we come across such printer configurations.

refactor: hide PA input fields if extruder_stepper is configured

---

src/components/TheEditor.vue

fix: restart services with name matching files

---

src/App.vue
src/assets/styles/page.scss
src/main.ts
src/pages/Machine.vue

fix: fix some gui issues

---

src/components/panels/GcodefilesPanel.vue
src/components/settings/SettingsDashboardTab.vue
src/components/settings/SettingsDashboardTabDesktop.vue
src/components/settings/SettingsDashboardTabMobile.vue
src/components/settings/SettingsDashboardTabTablet.vue
src/components/settings/SettingsDashboardTabWidescreen.vue
src/components/settings/SettingsMacrosTabExpert.vue

- replace old drag handles with proper dragging icons
- GcodefilesPanel.vue, SettingsMacroTabExpert, SettingsDashboardTab (multiple)
- always show drag handles
- truncate text if viewport too narrow
- bugfix: it was possible to toogle viewports on and off
- cursor style becomes "move" on hover over drag handle

refactor: replace drag handle icons

---

src/components/inputs/MacroButton.vue
src/components/panels/MacrogroupPanel.vue
src/components/panels/MacrosPanel.vue
src/components/settings/SettingsMacrosTabExpert.vue
src/components/settings/SettingsMacrosTabSimple.vue
src/store/printer/getters.ts

fix: macro buttons with single char attribute

---

src/components/panels/StatusPanel.vue

fix: display status tab on dashboard as default while printing

---

src/locales/en.json

locale(en): remove unused keys in EN locale

---

src/components/TheEditor.vue

fix: editor safe & restart with multi instances

---

package-lock.json
package.json
src/components/inputs/Codemirror.vue

Hi,
this PR contains code to add css file support for the editor. It is more comfortable when editing themes.
I also added a screenshot from my development environment.
Thanks

feat(editor): add .css language support

---

src/components/panels/GcodefilesPanel.vue

a long time ago, klipper cannot handle files with spaces in the path. looks like we forget to remove this rule in this panel.
fix: #941

fix: create folders with spaces in the name

---

Dockerfile

This fixes the failed docker Builds caused by https://github.com/mainsail-crew/mainsail/pull/949.
As a bonus, this also speeds up the build process itself.   
The nature of the node application allows the generated static files to be used on multiple architectures. Therefore, they only need to be built once and then copied into the platform specific runtime images. 
Have a look at the test build I did: 
* Pipeline: https://github.com/mkuf/mainsail/runs/7250954266?check_suite_focus=true
* Image: https://github.com/mkuf/mainsail/pkgs/container/mainsail/27950035?tag=edge
-Markus

docker: set platform for build target

---

src/components/panels/Machine/ConfigFilesPanel.vue

fixes #937
some refactoring was also done to fix some weaker IDE warnings.
there is still one warning about a deprecated "slot" symbol:
https://github.com/th33xitus/mainsail/blob/eda51cb85d565f0a05898c8eeea42232fa88cd8b/src/components/panels/Machine/ConfigFilesPanel.vue#L117
i wasn't sure how to approach that though. @meteyou maybe you have an idea? would be nice if we get that fixed before merging as well.

feat: allow collapsing of config file panel

---

.github/DEVELOPER_CERTIFICATE_OF_ORIGIN.md
CONTRIBUTING.md

Update the contribution guidelines.

chore: update CONTRIBUTING.md

---

package-lock.json
package.json
src/components/inputs/MiscellaneousSlider.vue

fix: max_power setting in miscellaneous panel

---

src/components/panels/Timelapse/TimelapseFilesPanel.vue

fix(timelapse): renaming a .zip file caused extension to become .mp4

---

src/components/inputs/MacroButton.vue
src/components/panels/ExtruderControlPanel.vue

Fixes #988
We loose the currently used icons on the old buttons.
Does it really matter? I don't think so. They didn't fit 100% perfectly anyways.
The improvements we achieve with this PR are far more usefull.

feat: improve load/unload filament button logic in Extruder panel

---

src/components/panels/Machine/LogfilesPanel.vue

Fixes #979
This PR will add a download button for crowsnest.log and sonar.log:
Those button appear under the following conditions:
crowsnest.log exists in the logfile directory
sonar.log exists in the logfile directory and its filesize is greater than 0

feat: download button for crowsnest.log and sonar.log

---

src/components/panels/ToolheadControls/ZoffsetControl.vue

This PR will fix issue #973. It is likely more intuitive for a lot of other users as well.
* Chrome 102.0.5005.63
* Firefox 101.0.1

refactor: reverse order of negative offset values in inline z-offset value layout

---

src/components/mixins/dashboard.ts
src/pages/Dashboard.vue

If all Temperature sensors start with `_` an empty `TemperaturePanel` was shown.
Signed-off-by: Manuel Thomassen <thom@ssen.codes>

fix: hide TemperaturePanel if no sensors would be shown

---

src/components/panels/TemperaturePanel.vue

For some reason the `v-divider` inside of the `v-menu` is rendered transparent and you can see the text underneath the `v-menu` through it.
Probably due to the case that it is set by Vuetify that way.
The expected behavior though would be, that the background color of the `v-menu` gets respected. Which, for some reason, is not the case. Presumably this might be a bug with Vuetify?
This PR solves the issue with applying a background color to that `v-divider` element as a workaround.

fix: divider in temperature presets is transparent

---

.env.development.local.example
public/config.json
src/App.vue
src/components/TheSelectPrinterDialog.vue
src/components/mixins/base.ts
src/components/settings/SettingsRemotePrintersTab.vue
src/components/ui/PrinterSelector.vue
src/locales/de.json
src/locales/en.json
src/main.ts
src/store/actions.ts
src/store/gui/actions.ts
src/store/gui/remoteprinters/actions.ts
src/store/index.ts
src/store/mutations.ts
src/store/types.ts

refactor: change remoteMode to instancesDB in config.json

---

src/components/panels/Machine/SystemPanelHost.vue

old output:
new output:
problem is the output of moonraker in the case of armbian (armbian is not LSB conform):
an example for a real LSB output from mainsailOS:

fix: distro output for armbian in SystemPanel

---

src/components/settings/SettingsWebcamsTab.vue

The `align-center` class caused some misalignment
Solution:
~~I haven't located the culprit of that cursor and label misalignment though, this is present in multiple input fields with form validation. It might be an issue introduced by ourself or a general Vuetify issue?~~
Located and fixed with: https://github.com/mainsail-crew/mainsail/pull/1020
Places the Target FPS and Rotate input fields into one line
A single line per input wastes a lot of space and is not even required on very small screen resolutions.

fix: webcam name input alignment

---

src/components/inputs/MoveToInput.vue

The solution does remove a css style that was applied to the label which was overwriting the font size of the label from 16px to 14px. Before we merge, we should re-evaluate if we want that again or if we apply the global 16px.

fix: global form validation error misalignment

---

src/components/inputs/MoveToInput.vue
src/components/panels/ToolheadControls/MoveToControl.vue

The input was validated against `position_min` and `position_max` of the configuration file. If the input falls below / exceeds the boundaries set inside the config, a visible error would be shown.
The real issue is, that those errors are also shown if there wasn't input from the user. The culprit in that case seems to be Klipper. The error was often reported, but wasn't possible to reproduce but looked like this:
It is suspected to be a rounding error in Klipper, hence Klipper actually reporting the wrong toolhead position which then appears to exceed the position_max by 0,01 which is enough to trigger an error during the validation methods. This often led to confusion for the user because the error simply was not comprehensible.
So the current solution aims at removing all validation …

refactor: remove input validation from MoveToInput

---

package-lock.json
package.json
src/components/gcodeviewer/Viewer.vue

feat: add exclude objects in G-Code Viewer

---

src/locales/de.json
src/locales/en.json
src/store/server/history/getters.ts

fix: combine small entries in history pie chart

---

src/components/settings/SettingsMacrosTabExpert.vue

fix: use background to fix border issues between the elements

---

src/components/panels/StatusPanel.vue

Fixes missing bottom border radius in the status panel.

fix(UI): missing bottom border radius in status panel

---

src/components/inputs/MiscellaneousSlider.vue
src/components/inputs/TemperatureInput.vue
src/components/inputs/ToolSlider.vue
src/components/panels/TemperaturePanel.vue

This PR tweaks a few font sizes, primarily the ones of the temperature input field and the slider input fields so they are 1rem / 16px tall. This should fix #1038
The font of the state message was increased to 14px, so its identically to the fontsize of the current temperature.
Also the font size of the presets accessible via the dropdown to the right hand side of the temperature input fields were increased to 14px.

fix(UI): tweak font sizes

---

src/main.ts
src/plugins/build-version.ts
src/plugins/helpers.ts
src/store/actions.ts
src/store/editor/actions.ts
src/store/farm/index.ts
src/store/farm/printer/actions.ts
src/store/files/actions.ts
src/store/files/getters.ts
src/store/gui/actions.ts
src/store/gui/console/getters.ts
src/store/gui/macros/actions.ts
src/store/gui/notifications/getters.ts
src/store/gui/remoteprinters/actions.ts
src/store/index.ts
src/store/server/actions.ts
src/store/server/history/actions.ts
src/store/server/history/getters.ts
src/store/server/jobQueue/actions.ts
src/store/server/mutations.ts
src/store/server/timelapse/actions.ts

refactor: fix lint issues

---

src/components/panels/KlippyStatePanel.vue
src/locales/da.json
src/locales/de.json
src/locales/en.json
src/locales/es.json
src/locales/fr.json
src/locales/hu.json
src/locales/it.json
src/locales/ja.json
src/locales/ko.json
src/locales/nl.json
src/locales/pl.json
src/locales/ru.json
src/locales/sv.json
src/locales/tr.json
src/locales/uk.json
src/locales/zh.json
src/locales/zh_TW.json

Often there is quite a bit confusion about error messages. Users often think, those messages come from Mainsail, although they are either directly coming from Klipper or Moonraker. This PR has the goal to make it a bit more clear where the errors come from. For that, the Klippy State Panel was reworked quite drastically. Depending on the status, different colors were choosen. Additionally, it is now possible to directly download the Klipper and/or Moonraker logfiles from that panel.
A simple title should make it more clear, which component is reporting the corresponding message and in turn make it more clear for the user.

refactor: rework of the KlippyState panel

---

src/components/TheEditor.vue
src/store/variables.ts

Will fix #1047 
https://github.com/Klipper3d/klipper-translations/blob/translations/active_translations

refactor(editor): use the config reference link of a translated version if it exists

---

src/components/panels/KlippyStatePanel.vue

refactor(KlippyStatePanel): display buttons as outlined text buttons

---

src/pages/Heightmap.vue

fix(Heightmap): flat for bed mesh not displayed if only one probe count set

---

src/locales/ja.json

locale(ja): update Japanese localization

---

src/components/webcams/Uv4lMjpeg.vue

This fixes a problem introduced in v2.4.0 for webcams defined with service `Uv4l-Mjpeg`, and will fix #1156.
Signed-off-by: Cor Ruiten <zozo@ruiten.com>

Fix: bad printerUrl check in ternary operator

---

src/locales/de.json
src/locales/en.json
src/pages/Heightmap.vue

refactor: rename variance to range in heightmap

---

src/components/TheTopbar.vue

Fixes #932
Not sure if people now will suddenly stop misinterpreting this icon as a notification icon on mobile view. But there was the request, so lets try it. _shrug_

refactor: replace emergency stop icon

---

src/components/TheEditor.vue
src/plugins/codemirrorTheme.ts

updates the search panel to also be properly themed. 
@th33xitus updated and created new PR.

fix: add theming for find/search panel Search panel

---

src/pages/Heightmap.vue
src/store/gui/index.ts
src/store/gui/types.ts

- saves the z-max heightmapScale. 
- increased the scale size to 2mm. useful for follks with not very flat beds.

fix(Heightmap): save z scale setting

---

src/components/panels/ToolheadControls/CircleControl.vue

fix for circle toolhead control to disable when not homed and when printing.

fix: disable circle control while printing or not homed

---

src/components/panels/TemperaturePanel.vue

fix: hide temperature sensors with `_` at first char

---

package-lock.json
package.json
src/components/panels/GcodefilesPanel.vue
src/components/panels/Machine/ConfigFilesPanel.vue
src/components/panels/Timelapse/TimelapseFilesPanel.vue
src/store/editor/actions.ts

feat: add multi download to ConfigFilesPanel.vue

---

src/components/charts/HistoryAllPrintStatusChart.vue
src/components/charts/HistoryAllPrintStatusTable.vue
src/components/panels/HistoryStatisticsPanel.vue
src/locales/en.json
src/store/gui/index.ts
src/store/gui/types.ts
src/store/server/history/getters.ts

this PR will fix #891 
Chart view:
Table view:

feat: add table view for print status stats

---

package-lock.json
package.json
src/components/gcodeviewer/CodeStream.vue
src/components/gcodeviewer/Viewer.vue
src/locales/en.json
src/store/gui/index.ts
src/store/gui/types.ts

A new panel was added to the G-Code Viewer to stream the current viewed G-Code.
When simulating a file the cursor will now move to follow the print.
New version of library which includes voxel viewing fix.
Added new ShowGCode i18n entry
Added showGCodePanel to persist property in store

Add new CodeStream control to Gcodeviewer

---

package-lock.json
package.json
src/components/gcodeviewer/Viewer.vue
src/locales/en.json
src/store/gui/index.ts
src/store/gui/types.ts

This will support g-code visualization for routers and lasers. This mode forces line rendering until non-planar rendering is complete.

Add support for CNC Mode

---

src/components/mixins/base.ts
src/components/panels/KlippyStatePanel.vue
src/components/settings/SettingsUiSettingsTab.vue
src/locales/de.json
src/locales/en.json
src/store/gui/index.ts
src/store/gui/types.ts

fixes #897
screenshot of the dashboard panel:
screenshot from the interface setting:

feat: add power button on dashboard to switch printer on

---

src/components/webcams/Hlsstreamer.vue

The HLS Streamer's video latency increases over time. By leaving the browser tab open, the latency would add up to a few minutes over time. With the defautl settings, HLS.js never catches up to the edge and continues playing at 1x speed despite being minutes late.
By adding these configuration options, the latency is limited to 2 seconds.
from HLS.js documentation, this is what these changes should achieve:
```
{
"enableWorker": true, // actually defaults to true, but hls.js examples typically include this setting anyway. 
"lowLatencyMode": true, // Enable Low-Latency HLS part playlist and segment loading, and start live streams at playlist PART-HOLD-BACK rather than HOLD-BACK.
"maxLiveSyncPlaybackRate": 2, // Enables catching-up to the edge by enabling up to 2x playback (defaults to 1) …
```

HLS streamer - improve latency

---

src/components/panels/ExtruderControlPanel.vue
src/store/printer/getters.ts
src/store/printer/types.ts

When set the button color will use that set from the variable.
Example macros
```
############################################################################
############################################################################
[gcode_macro _SET_ACTIVE_TOOL]
description: Sets the active tool in mainsail (and all others inactive)
gcode:
{% set TOOL = params.TOOL|default(-1)|int %}
{% for T in range(9) %}
{% if T == TOOL %}
SET_GCODE_VARIABLE MACRO=T{T} VARIABLE=active VALUE=1
{% else %}
SET_GCODE_VARIABLE MACRO=T{T} VARIABLE=active VALUE=0
{% endif %}
{% endfor %}
[gcode_macro _SET_TOOL_COLOR]
description: Sets a color for mainsail extruder
gcode:
{% set tool = params.TOOL|default(-1)|int %}
{% set ns = namespace(color="undefined") %}
{% for param in rawparams.split(' ') %}
{% if …
```

feat: support a color or colour variable from tool change macros

---

src/components/panels/StatusPanel.vue

split M117 output and print_stats.messages to have better identification
fixes #1308

fix: missing M117 output in status panel

---

src/components/dialogs/TheScrewsTiltAdjustDialog.vue
src/store/printer/mutations.ts

fix: fix issue of empty Screws tilt adjust helper dialog

---

src/components/panels/GcodefilesPanel.vue
src/components/panels/Machine/ConfigFilesPanel.vue
src/components/panels/Timelapse/TimelapseFilesPanel.vue

Some input dialogs have issues when i typed in an invalid name and/or open the same dialog multiple times. The input check will disable the "save/update" button.

fix: fix invalid name input checks

---

src/components/settings/SettingsUiSettingsTab.vue

Current link https://docs.mainsail.xyz/quicktips/thumbnails gives 404, and https://docs.mainsail.xyz/overview/features/thumbnails has links to slicer instructions

fix: fix thumbnail guide link in settings

---

src/components/panels/Machine/ConfigFilesPanel.vue

This PR fixes the timestamp format used for zip downloads. Previously, the date components were not padded with zeroes and the month was off by 1 because ``Date.getMonth()`` reports months from 0 to 11. This PR aligns the used timestamp format with [the one used by Moonraker](https://github.com/Arksine/moonraker/blob/6c7dfe592131eb95fd760ef2db83387966b250f0/moonraker/components/file_manager/file_manager.py#LL601C15-L601C15), making it more readable and also fixing the sorting.
Example for a previous timestamp: ``config-202344-17137.zip``
After change: ``config-20230504-170137.zip``
None

fix: fix zip file timestamp

---

src/store/files/actions.ts

The wrong notification was being shown when moving a file, this PR makes sure that the "file move" toast shows when we move a file instead of the rename toast.
**Before**
https://user-images.githubusercontent.com/15934114/236298842-801fef15-c3b2-4f71-a6cd-7aa4e3017efa.mov
**After**
https://user-images.githubusercontent.com/15934114/236298867-29985bd1-417f-457e-9143-ab8f11ba620f.mov
No post deployment tasks.

fix: Make the correct notification appear on gcode file move

---

src/store/files/actions.ts
src/store/files/mutations.ts

This PR fix the a but when moving a file from a subdirectory to the root directory (specially when the file was the first (or only) file in the directory.
This PR fixes #1374

fix: fix issue when moving a file to the root directory

---

src/store/variables.ts

Adds the AHT10 family of sensors to `additionalSensors`, allowing the humidity reported to be shown.  Tested on an AHT20 sensor, but Klipper treats them all the same, as an AHT10.
https://www.klipper3d.org/Config_Reference.html?h=aht20#aht10aht20aht21-temperature-sensor
Signed-off-by: Ben Phelps <ben@phelps.io>

feat: Add AHT10 to additionalSensors

---

package-lock.json
package.json
src/components/panels/WebcamPanel.vue
src/components/settings/SettingsWebcamsTab.vue
src/components/webcams/JMuxerStream.vue
src/components/webcams/WebcamGrid.vue
src/locales/da.json
src/locales/de.json
src/locales/en.json

This PR implements a new webcam type: jmuxer-stream.
This type of webcam uses JMuxer.js (https://github.com/samirkumardas/jmuxer) to support streaming a "raw" h264 stream (h264 Elementary Stream).
The patch is tested, and works locally. Translations are added for English, Danish and German.
The new webcam type integrates fully with the existing webcam settings panels, etc, although advanced features on jmuxer do not have a ui control.
Certain printers, like AnkerMake M5, need this camera type, to support streaming.
If you're wondering how AnkerMake M5 comes into the picture (no pun intended..), it's because we (https://github.com/ankermgmt/) are working on a Moonraker API implementation, allowing Mainsail to serve as a frontend for the printer.
All that is needed, is this webcam type. …

feat: add jmuxer-stream webcam type, supporting raw h264

---

src/components/panels/GcodefilesPanel.vue
src/locales/de.json
src/locales/en.json
src/store/files/actions.ts

When viewing a mounted network drive gcode files that are added to the network share and not uploaded via Mainsail do not contain any meta data or thumbnails. 
This was originally raised as an issue within Moonraker https://github.com/Arksine/moonraker/issues/614 and determined to be an issue with some mount options, for example cifs, did not properly run inotify events which moonraker relies on. 
There was already a moonraker API endpoint /server/files/metascan that can scan existing files so we just added the option to right click and scan meta data via Mainsail instead of trying to cover every mount type and inotify compatibility issues.

feat: add facility to Scan Metadata from G-code Files

---

src/components/charts/TempChart.vue
src/components/settings/SettingsUiSettingsTab.vue
src/locales/de.json
src/locales/en.json
src/store/gui/index.ts
src/store/gui/types.ts

This PR add an option in the interface settings (UI-Settings) to modify the height of the Temperatur-Chart on the Dashboard.
Fixes #1390

feat: add an option to change the height of the temperatur chart

---

CONTRIBUTING.md

The current CONTRIBUTING.md URL goes to a 404 page. This PR updates the link to the correct location.

fix: broken coding standards link in contributing doc

---

src/components/webcams/WebrtcCameraStreamer.vue

This PR updates the `camera-streamer` WebRTC signaling to take advantage of the new features in [v0.2.4](https://github.com/ayufan/camera-streamer/releases/tag/v0.2.4); including:
1. Faster webcam stream start time (trickle ICE)
2. Full ICE server support
This change is forward and backward-compatible with camera-streamer versions.
JS isn't my language specialty, so please feel free to update anything that could be improved. :)
Camera-streamer version  [v0.2.4.](https://github.com/ayufan/camera-streamer/releases/tag/v0.2.4)
None
None

feat: Updating the WebRTC camera component with camera-streamer's WebRTC signaling protocol.

---

src/App.vue
src/store/farm/printer/actions.ts
src/store/files/mutations.ts

Mainsail sent empty metadata requests. This PR should fix this bug. This bug was in the farm printers module.
no open issue.

fix: check only not empty filename for metadata in farm printers

---

src/locales/zh.json

I found bugs in some translations, so I fixed them.

locale(zh): fix translation

---

src/components/mixins/navigation.ts

This PR fix the issue to display the `/allPrinters` navigation point in the sidebar again.
none

fix: fix navigation to display allPrinters

---

src/components/panels/FarmPrinterPanel.vue

This PR removes a unused import in FarmPrinterPanel.vue.
none
none

refactor: remove unused import in FarmPrinterPanel.vue

---

src/components/dialogs/TheScrewsTiltAdjustDialog.vue
src/locales/de.json
src/locales/en.json

This PR adds a button "retry" to the ScrewsTiltAdjust helper dialog to rerun `SCREWS_TILT_CALCULATE`.
fixes #1414

feat: add retry button to ScrewsTiltAdjust helper dialog

---

src/App.vue
src/components/TheServiceWorker.vue
src/locales/de.json
src/locales/en.json
src/main.ts
vite.config.ts

This PR add PWA workbox to cache all assets to run Mainsail offline and add a updater function/dialog.
no related tickes

chore: add PWA caching and cache updater

---

package-lock.json
package.json
vite.config.ts

This PR add some missing settings in the vite pwa settings:
- switch to strategie generateSW
- add maximumFileSizeToCacheInBytes
- add suppressWarnings
none
none

chore(pwa): remove debug warnings in browser console

---

src/plugins/StreamParserKlipperConfig.ts

This PR removes the jinja parsing of gcode variables. I think this is not necessary, because there is no jinja syntax possible. 
fixes #1433

fix: remove variable check in klipper config StreamParser

---

src/plugins/build-release_info.ts
vite.config.ts

This PR adds a release_info.json file in the /dist directory. 
none
with this content:
```json
{"project_name":"mainsail","project_owner":"mainsail-crew","version":"v2.6.0"}
```

refactor: build version file for moonraker

---

src/components/TheEditor.vue

Updated the condition in the restartServiceNameExists getter in TheEditor.vue component. Previously, it was returning true if 'restartServiceName' exists. However, this was incorrect as the function should return true only when 'restartServiceName' does not exist. This change fixes an issue where the available services were not correctly checked if 'restartServiceName' existed.
This PR fixes #1432 
none
none

fix: fix condition in restartServiceNameExists check

---

.gitignore

This commit adds 'dev-dist' directory to .gitignore. 'dev-dist' is a folder that gets created when we build the application in development environment, it's not needed to be tracked as it only contains generated files.
none
none

chore: add dev-dist to .gitignore

---

src/App.vue
src/components/panels/StatusPanel.vue
src/store/farm/printer/getters.ts
src/store/getters.ts

The existing implementation will report 100% from 99.5% on, due to round(). Switching to floor() instead, which will report 99% until complete.
This PR fixes a display bug where prints will report 100% anytime they are at 99.5% or higher.
There is a Discord support thread: 
https://discord.com/channels/758059413700345988/1126955424999035061
no

fix: avoid hitting 100% before print is complete

---

src/locales/zh.json

locale(zh): Update Chinese (zh) localization

---

src/components/mixins/base.ts
src/components/panels/HistoryListPanel.vue

This PR escape CSV separator in the content fields
fixes comment issue in #963

fix: fix issue with CSV separator in contents

---

src/components/mixins/webcam.ts
src/components/panels/FarmPrinterPanel.vue
src/components/webcams/Hlsstreamer.vue
src/components/webcams/Ipstreamer.vue
src/components/webcams/JMuxerStream.vue
src/components/webcams/Mjpegstreamer.vue
src/components/webcams/MjpegstreamerAdaptive.vue
src/components/webcams/Uv4lMjpeg.vue
src/components/webcams/WebcamWrapper.vue
src/components/webcams/WebcamWrapperItem.vue
src/components/webcams/WebrtcMediaMTX.vue

all printers show the same webcam after switching the printer.
Bugreport on the klipper discord: https://discord.com/channels/431557959978450984/704747457795588100/1125753077769707590
none

fix: fix issue with webcams in farm printers

---

src/components/charts/TempChart.vue
src/components/panels/Temperature/TemperaturePanelList.vue
src/components/panels/Temperature/TemperaturePanelListItem.vue
src/components/panels/Temperature/TemperaturePanelListItemAdditionalSensor.vue
src/components/panels/Temperature/TemperaturePanelListItemAdditionalSensorValue.vue
src/components/panels/Temperature/TemperaturePanelListItemEdit.vue
src/components/panels/Temperature/TemperaturePanelListItemEditAdditionalSensor.vue
src/components/panels/Temperature/TemperaturePanelListItemEditChartSerie.vue
src/components/panels/Temperature/TemperaturePanelPresets.vue
src/components/panels/Temperature/TemperaturePanelSettings.vue
src/components/panels/TemperaturePanel.vue
src/components/ui/Panel.vue
src/store/gui/actions.ts
src/store/gui/getters.ts
src/store/gui/mutations.ts
src/store/printer/getters.ts
src/store/printer/tempHistory/actions.ts
src/store/printer/tempHistory/getters.ts

Split the TemperaturePanel
none
none

refactor: extract Presets and Settings from TemperaturePanel

---

src/components/TheEditor.vue
src/components/settings/SettingsEditorTab.vue
src/locales/cz.json
src/locales/da.json
src/locales/de.json
src/locales/en.json
src/locales/es.json
src/locales/fr.json
src/locales/hu.json
src/locales/ja.json
src/locales/ko.json
src/locales/nl.json
src/locales/pl.json
src/locales/pt.json
src/locales/ru.json
src/locales/sv.json
src/locales/tr.json
src/locales/uk.json
src/locales/zh.json
src/locales/zh_TW.json
src/store/editor/actions.ts
src/store/editor/getters.ts
src/store/gui/index.ts
src/store/gui/types.ts

This PR fix the behavior of the Save & Restart button for multi instances.
none
none

fix: fix editor save & restart button behavior

---

src/components/settings/SettingsRow.vue

add type TranslateResult to title and subTitle and refactor template
This PR just refactor the SettingsRow.vue
none
none
none

refactor: refactor SettingsRow

---

src/components/panels/Temperature/TemperaturePanelListItem.vue

In the last refactoring of the temperature panel is a bug, which display `NaN RPM` when your temperature_fan has no tachometer.
none
none
none

fix: hide rpm in temperature_fans without tachometer_pin

---

src/components/mixins/webcam.ts
src/components/webcams/Hlsstreamer.vue
src/components/webcams/Ipstreamer.vue
src/components/webcams/JMuxerStream.vue
src/components/webcams/JanusStreamer.vue
src/components/webcams/Mjpegstreamer.vue
src/components/webcams/MjpegstreamerAdaptive.vue
src/components/webcams/Uv4lMjpeg.vue
src/components/webcams/WebrtcCameraStreamer.vue
src/components/webcams/WebrtcMediaMTX.vue

This PR fix the flip function in all webcam clients except MjpegstreamerAdaptive.
fixes #1485 
none
none

fix: fix flip funciton in several webcam clients

---

src/components/panels/Temperature/TemperaturePanelListItem.vue

This PR fix the issue with not lowercase object names in temperatur panel
none
none
none

fix: fix issue with camel-case object names in temperature panel

---

src/components/settings/SettingsTimelapseTab.vue
src/store/gui/webcams/actions.ts
src/store/server/timelapse/actions.ts

This PR fix the timelapse settings. The Moonraker webcam API don't serve the UUID of the webcams, so the timelapse plugin and the Mainsail settings page have to switch to the name.
none
none
none

fix: use webcam name instead of UUID for timelapse plugin 

---

src/components/panels/Machine/UpdatePanel/Entry.vue
src/components/panels/Machine/UpdatePanel/GitCommitsListDayCommit.vue
src/components/panels/Machine/UpdatePanel/UpdateHintAlert.vue
src/locales/en.json
src/store/server/updateManager/types.ts

This PR fixes multiple issues in the update manager:
- remove warnings from mainsail, because moonraker post the same one
- add anomalies to each entry (if exists)
- fix issues with wrong links to github pages
- fix button text when the state is dirty
none
- it would be nice to have a PR to moonraker to add more informations to the default corrupt, detached and dirty messages (like the old one before from mainsail)

fix: fix multiple issues in the refactored update manager

---

src/store/printer/actions.ts

After a Klipper firmware_restart/restart and the extruder temp is higher than the min_extrude setting, Moonraker/Klipper only init the extruder with `can_extrude: false` but don't update it. With this PR, i send a delayed reinit request to update this attribute. This is more a "hack" then a fix, because the fix would have to be in Moonraker/Klipper itself.
fixes #1490 
none
none

fix: fix issue with extruder cannot extrude after a klipper restart

---

src/components/dialogs/TheScrewsTiltAdjustDialog.vue

With this PR, Mainsail will hide the SCREWS_TILT_ADJUST helper dialog, when using MAX_DEVIATION
This PR fixes #1472 
none
This PR requires a merge of this PR (https://github.com/Klipper3d/klipper/pull/6295) into Klipper.

feat: hide screws tilt adjust helper dialog, when using MAX_DEVIATION

---

src/components/panels/Temperature/TemperaturePanelList.vue
src/components/panels/Temperature/TemperaturePanelSettings.vue
src/locales/de.json
src/locales/en.json
src/store/gui/index.ts
src/store/gui/types.ts
src/store/printer/tempHistory/getters.ts

Add an option to hide all MCU or Host temperature sensors in the temperature panel.
fixes #1464 
option disabled:
option enabled:
none

feat: add option to hide MCU & Host sensors in the temperature panel

---

src/components/panels/ToolheadControlPanel.vue
src/components/settings/SettingsControlTab.vue
src/locales/de.json
src/locales/en.json
src/store/gui/index.ts
src/store/gui/types.ts

This PR adds a setting to hide the axis controls (X, Y, Z) instead of only disabling it during a print. The Z-Offset controls are not affected. This saves some space on the screen, especially on mobile devices.
Settings:
Toolhead panel in ready state:
Toolhead panel in printing state with hiding setting on:
Toolhead panel in printing state with hiding setting off:

feat: hide axis controls during print

---

src/components/settings/Webcams/WebcamForm.vue
src/components/webcams/Mjpegstreamer.vue
src/components/webcams/MjpegstreamerAdaptive.vue
src/locales/de.json
src/locales/en.json
src/store/gui/webcams/types.ts

This PR add an option for each mjpegstreamer webcam to hide the FPS counter.
fixes #1473
none

feat: add option to hide FPS counter

---

src/components/panels/Machine/UpdatePanel/Entry.vue
src/components/panels/Machine/UpdatePanel/EntrySystem.vue

This PR change all version links to info color (blue) and the moonraker anomaly button to gray. also the message will have a gray background.
https://github.com/mainsail-crew/moonraker-timelapse/issues/128

refactor: soft down info buttons in update manager

---

src/components/TheSidebar.vue

This PR fixes an issue with the sidebar on tablets and smaller devices. If you click a navi point and the sidebar will hide, the space behind the sidebar will not be blank anymore. The sidebar will push the new state to the Vuex store to remove the padding left of the main container.
none open issues
before:
after:

fix: fix issue on tablet and smaller devices with the sidebar

---

src/components/TheTopbar.vue

This PR fixes the emergency stop diaglog showing up, even when its disabled in the settings.
Right now with the option disabled the dialog showed up but the ermergency stop was already emited to moonraker.
https://discord.com/channels/758059413700345988/1143208722676580392

fix: show confirm emergency stop dialog only when turned on

---

src/store/gui/getters.ts

This PR fixes the time format detection from browser. 
Right now the time format of the ETA time field won't be adjusted to the browser settings and will fallback to default 24hrs format. To fix this we read the `LocaleTimeString()` to determine the current format and adjust the setting accordingly.
https://discord.com/channels/758059413700345988/1139732350515818506

fix: eta time format detection from browser

---

src/pages/Heightmap.vue

This PR fix the min/max positions in the heightmap page in the "current mesh" panel. The calculation of the position from the datapoints was incorrect.
fixes #1520

fix: fix min/max positions in heightmap current mesh data panel 

---

src/components/webcams/WebrtcCameraStreamer.vue

This webcam mode should restart after 5 seconds, if the connection is failed or disconnected, but there was a bug, that it only restart one time.
none
none
none

fix: fix autorestart of webcam camerastreamer

---

src/components/settings/General/GeneralReset.vue
src/locales/en.json

This PR adds the options for reset the print history datas again. We lost these options in this PR #1448 
none

fix: fix missing reset options for print history data

---

src/components/inputs/ToolSlider.vue
src/components/panels/ToolheadControlPanel.vue

This PR just cleanup the ToolheadControlPanel.vue file
none
none
none

refactor: refactor ToolheadControlPanel

---

src/components/inputs/MacroButton.vue

This PR fixes an issue, if you try to send a macro parameter via Mainsail, which contain a space in it.
fixes: #1550 
none

fix: fix macro parameter with spaces

---

src/components/panels/ToolheadControls/ZoffsetControl.vue

This PR will hide the sub menu of the gcode offset save function and only use the right store function depends on your stepper_z endstop pin definition.
none
none
none

feat: automatic selection of the gcode offset save gcode

---

src/components/TheTopCornerMenu.vue

This PR add a filter to hide all Moonraker power devices with a `_` as first char.
fixes: #1543 
none
none

feat: hide Moonraker power devices with a `_` as first char

---

src/components/panels/MiniconsolePanel.vue
src/locales/en.json
src/pages/Console.vue
src/store/gui/console/index.ts
src/store/gui/console/types.ts

Signed-off-by: meteyou <meteyou@gmail.com>
This PR adds an option to block auto-scroll in the console in the "bash" mode.
This PR fixes #838 
Option in miniconsole panel:
Option in the console page:

feat: add option to block autoscroll in console

---

src/components/panels/Temperature/TemperaturePanelListItem.vue

This PR just fix a 'Unexpected null' type issue in the TemperaturePanelListItem.vue
none
none
none

fix: fix type issue in TemperaturePanelListItem

---

src/components/webcams/WebrtcCameraStreamer.vue

This PR fix the autorestart mechanism of the webcam client camera-streamer.
none
none

fix: fix webcam (camera-streamer) stop autorestart beforeDestory

---

src/components/panels/Temperature/TemperaturePanelPresets.vue

This PR fix the G-Code in presets for generic_heaters.
fixes #1567 
none

fix: fix gcode command for generic_heater in presets

---

src/store/farm/printer/getters.ts

Add the 12-hour time format to the printers overview ETA.
fixes: #1570 
none

feat: add 12-hour time format in printers overview

---

src/store/printer/getters.ts

This PR just remove an unused import in store/printer/getters.ts.
none
none
none

refactor: remove unused import in store/printer/getters.ts

---

.github/dependabot.yml

This adds https://docs.github.com/en/code-security/dependabot to the repository to easily update packages.

build(dependabot): add Dependabot to the repository

---

src/components/webcams/WebrtcCameraStreamer.vue

This PR fix the printer URL in webcam settings for external access (or also for debug mode).
none
none

fix: WebRTC (camera-streamer) port with external mainsail instance

---

.github/workflows/release.yml

This PR fixes the release workflow. The version number from the FTP step is needed to use this action.
- failed workflow run: https://github.com/mainsail-crew/mainsail/actions/runs/6442825302
none
none

chore: fix ftp upload in release workflow

---

.github/workflows/publish_docker.yml

It seems that the recent version haven't been tagged as Docker images correctly. This PR should resolve that.
See: https://github.com/docker/metadata-action?tab=readme-ov-file#typesemver

ci(docker): ensure that the docker images are tagged correctly

---

src/components/dialogs/SpoolmanChangeSpoolDialog.vue
src/components/dialogs/SpoolmanChangeSpoolDialogRow.vue

Rework of the spoolman change dialog to display spool ids.
Changes the dialog to a similar style as the spoolman dashboard panel.
https://github.com/mainsail-crew/mainsail/issues/1604

feat: rework spoolman change dialog to display spool ids

---

src/components/dialogs/StartPrintDialogSpoolman.vue

This PR fix the filament type check for multi filament prints.
fixes #1617
Before:
After:

fix: fix filament type check in StartPrintDialog

---

.github/workflows/check-pr-title.yml

This PR add a workflow to check the PR title, that we can only merge PRs with a valid title to the develop branch.
none
none
none

chore: add workflow to check PR title for conventional commits spec

---

src/components/panels/ExtruderControlPanel.vue

Also allow `FILAMENT_LOAD` and `FILAMENT_UNLOAD` instead of `LOAD_FILAMENT` and `UNLOAD_FILAMENT` in the extruder panel.
none

refactor: also allow FILAMENT_LOAD and FILAMENT_UNLOAD macros

---

src/components/panels/ExtruderControlPanel.vue
src/locales/de.json
src/locales/en.json

This PR also add buttons for `CLEAN_NOZZLE` & `PURGE_FILAMENT` in the extruder panel (like `LOAD`/`UNLOAD_FILAMENT`).
none
none
Add all macros in the docs.

feat: add buttons for PURGE_FILAMENT and CLEAN_NOZZLE in extruder panel

---

src/components/mixins/navigation.ts
src/components/settings/SettingsNavigationTab.vue
src/store/gui/navigation/actions.ts
src/store/gui/navigation/mutations.ts

This PR fix the hide/show and sort function of the navigation in other languages. Only english works without this fix.
none
none
none

fix: fix hide/show navi points in different languages

---

src/store/gui/presets/actions.ts

This PR fix an issue, when you add multiple presets without a refresh.
maybe this PR will fix #1622 
none
none

fix: fix adding multiple presets

---

src/components/charts/TempChart.vue

This PR fix the tooltip in the tempchart. Right now, there are only the current temp and no target temp in it.
none
before:
after:
none

fix: fix wrong output in temp chart tooltip

---

src/components/mixins/base.ts
src/store/gui/getters.ts
src/store/printer/getters.ts

This PR fix the "fallback" detection for 12-hour format. This generate a wrong ETA time format for countries other than en-US in there browser languages and 12-hour time format.
Discord: https://discord.com/channels/758059413700345988/1174115244671504455/1174115244671504455
none
none

fix: fix ETA 12hour detection if the user use default browser settings

---

src/store/gui/getters.ts
src/store/printer/getters.ts

Fixes time format in ETA output in the status-panel. This should change 00:10 AM to 12:10 AM.
fixes: https://github.com/mainsail-crew/mainsail/issues/1461#issuecomment-1823767052
none
none

fix: fix 12-hour time format in ETA output

---

src/components/mixins/zoffset.ts
src/components/panels/ToolheadControls/ZoffsetControl.vue
src/components/settings/SettingsControlTab.vue
src/locales/en.json
src/store/gui/index.ts
src/store/gui/types.ts

This PR adds an option to change the auto z offset save method.
none
none

feat: add option to change the save z-offset method

---

.github/workflows/check-pr-title.yml

This PR change the action and settings for the check-pr-title workflow to allow locale as type.
none
none
none

chore: fix check-pr-title workflow to allow locale as type

---

src/components/panels/GcodefilesPanel.vue
src/components/panels/Machine/ConfigFilesPanel.vue
src/components/panels/Timelapse/TimelapseFilesPanel.vue
src/components/ui/PathNavigation.vue

This PR adds the feature requested in #1643, which allows to interactively use the "current path" (visible above the file browsers / explorer, eg. "GCode files" explorer) to quickly navigate to any segment of the path.
Path navigations allows for both mouse & keyboard usage (provides bare minimum of accessibility), allows to select the entire path (eg. to copy & paste it as text somewhere). It is also implemented as a reusable component, to both help with maintainability, and allow for future reuse in other places.
#1643
[Gcode files explorer (webm)](https://github.com/mainsail-crew/mainsail/assets/4425221/b1bf7f92-9a26-40bb-b0e4-a3d4e226023c)
[Config files explorer (webm)](https://github.com/mainsail-crew/mainsail/assets/4425221/cef25d4a-0736-4e0a-86a4-bb7ab3c19b5a)
N/A

feat: File browsers - add ability to quickly jump to any path segment

---

src/components/dialogs/StartPrintDialog.vue
src/store/variables.ts

Fix a issue with auto generated small thumbnails from Moonraker (some thumbnails only 31px height). Also stretch the large thumbnail in the StartPrintDialog.
none
none
none

fix: more tolerant with thumbnails sizes

---

src/components/panels/MachineSettings/MotionSettings.vue
src/locales/de.json
src/locales/en.json

This PR switch from `max_accel_to_decel` to `minimum_cruise_ratio`. The old field will be used as fallback, if no `minimum_cruise_ratio` exists.
none
Klipper PR for this feature: https://github.com/Klipper3d/klipper/pull/6418

feat: add minimum_cruise_ratio support in MotionSettingsPanel

---

src/components/inputs/FilamentSensor.vue
src/locales/de.json
src/locales/en.json

This PR changes the FilamentSensor view so the filament state (detected or empty) is shown regardless of whether the sensor is enabled or disabled. I added the "disabled" state next to the presence state simply because I'm unaware of an alternative way to show both together, let me know if there is an existing pattern I can re-use here.
I sometimes disable my filament motion sensors but I would still like to see whether the sensor reports motion or not. This can be useful when debugging filament run-out issues, for example when the detection length is too short and the filament sensor keeps triggering but the print is actually going fine.

feat: show filament sensor state even when the sensor is disabled

---

src/locales/de.json
src/locales/en.json
src/plugins/webSocketClient.ts
src/store/gui/notifications/getters.ts
src/store/server/actions.ts
src/store/server/index.ts
src/store/server/mutations.ts
src/store/server/types.ts
src/store/socket/actions.ts
src/store/socket/mutations.ts

This PR adds a check for failed Moonraker components, skip  the Initialization dialog and adds a warning for this component. A typical issue, when you need this feature is, when Moonraker has no connection to spoolman. Then Mainsail has to skip the init process of this module.
fixes: #1633 
none

feat: add moonraker init component check with warning

---

src/plugins/helpers.ts

Fixes message proccesing for the console output and removes special messages indicators only at the beginning of a message.

fix: add anchor to regex for special msg replacement

---

src/store/printer/getters.ts

Just remove a unused import in the printer/getters.
none
none
none

refactor: remove unused import from printer/getters

---

src/components/panels/StatusPanel.vue
src/locales/cz.json
src/locales/da.json
src/locales/de.json
src/locales/en.json
src/locales/es.json
src/locales/fr.json
src/locales/hu.json
src/locales/it.json
src/locales/ja.json
src/locales/ko.json
src/locales/nl.json
src/locales/pl.json
src/locales/pt.json
src/locales/ru.json
src/locales/tr.json
src/locales/uk.json
src/locales/zh.json
src/locales/zh_TW.json

Job queue tab has a counter displaying current items count. The counter itself works fine, however it's presented as a gray text, which blends with the background and neighboring text. This quite poor contrast might lead to poor reception of the counter functionality (eg. for me, I usually forget that I've put something in the queue, because the counter is nearly indistinguishable from the tab's label).
To improve the "contrast" (so to speak) of the feature, a simple Badge component can be used instead of text interpolation with the tab's title, allowing it to be displayed slightly different than the neighboring text (the "contrast" improvement comes mainly from the different element being used rather than just color change). This approach also allows it to change its background depending …

feat: Improve contrast of job queue items count

---

src/locales/de.json

Update de locale file.
none
none
none

locale(de): update german locale

---

src/store/printer/tempHistory/actions.ts

With this PR, Mainsail will generate random colors, if the colorArray is too small.
fixes #1673 
before:
after:
none

fix: add random colors, when colorArray is too small

---

src/components/panels/Status/Jobqueue.vue

This PR fixes a bug in the Jobs queue, where the "rest of jobs" does not correctly sum up estimated printing time of the rest files. Instead of summing up all of the rest jobs, it takes into account only the last element of the list.
Bug is caused by a simple omission of addition operator in code.
1. Place 5 random models into the Queue
- (so that the next item in the queue will not be displayed directly)
1. Add two more DISTINCT models with different estimated times
1. One with estimated print time of eg. 5h
1. One with estimated print time of eg. 1h
- Summed up estimation displays "6h of print time"
- Summed up estimation displays "1h of print time"
- Bug does not occur when adding the same model multiple times, that is, when `combinedIds` internal feature is being used.
N/A (no bug …

fix: Incorrect sum of rest jobs printing time

---

src/App.vue

This PR fixes a issue with the naviDrawer on tablet and smaller viewports.
fixes #1596
before:
after:
none

fix: fix panels squeezed on mobile when navi is open

---

src/components/settings/SettingsGeneralTab.vue

This PR fix the language switch for languages with files with more than 2 chars (like zh_TW).
fixes #1700 
none
none

fix: fix language switch

---

src/components/settings/SettingsGeneralTab.vue

This PR only remove an unused icon in the SettingsGeneralTab.vue
none
none
none

refactor: remove unused icon in SettingsGeneralTab.vue

---

src/components/mixins/extruder.ts
src/components/panels/Extruder/ExtruderPanelSettings.vue
src/components/panels/ExtruderControlPanel.vue

Only display existing options in the extruder panel.
none
none
none

fix: only display section options which exists in ExtruderPanel

---

src/components/webcams/streamers/Mjpegstreamer.vue
src/components/webcams/streamers/MjpegstreamerAdaptive.vue

This PR fix the aspectRatio, when you switch between different MjpegstreamerAdaptive webcams.
fixes #1701 
none
none

fix: fix aspectRatio in MjpegstreamerAdaptive

---

src/components/panels/Status/ExcludeObject.vue
src/components/panels/Status/ExcludeObjectDialogMap.vue
src/components/panels/StatusPanel.vue

This PR fix the order of parts in the exclude objects map. With this fix, you can click on smaller parts in bigger parts.
fixes #1477 
before:
after:
none

fix(exclude_objects): fix order of objects in map

---

src/components/panels/Status/ExcludeObjectDialogMap.vue

This PR fix the position of the tooltip in the exclude objects map.
fixes #1699 
none
none

fix(exclude objects): fix tooltip position in object map

---

.github/workflows/publish_docker.yml
.github/workflows/release.yml
Dockerfile

This PR fix the trigger from the release_docker.yml workflow. To trigger CI workflows, I had to add the PAT in the release action. I have also changed `npm install` to `npm ci` in docker build.
fixes: #1721 
none
none

build(docker): fix docker release tags

---

.github/workflows/release.yml

Update orhun/git-cliff-action action from v1 to v2. v1 doesn't have a postprocessor included.
fixes: #1696 
none
none

build(changelog): fix issue with wrong urls in changelog.md

---

src/store/gui/presets/getters.ts

This PR fix a parsing issue in the compare of preset temp to list only each temp one time in the heater input dropdown.
none
none
none

fix(temperature panel): hide multiple same temp presets in dropdown 

---

src/plugins/webSocketClient.ts

Before this PR, all requests with a return action which starts with `server/` could added to "init. Moonraker notification" (check the screenshot below. With this PR, it will be checked, if it is a initable Moonraker module, or another Moonraker/server module.
none
before this PR:
none

fix: only check initableServerComponents for init moonraker check

---

.github/label-actions.yml

This PR will update the GitHub Issue Tracker bot text for "not on github" to "not an Issue".
none
none
none

chore: update github issue bot text

---

src/components/panels/Machine/ConfigFilesPanel.vue

This PR fixes the squishing of big images in the config file preview window, now it will properly scale down the images while preserving the original aspect ratio instead of trying to make them fit by squishing them down.
Original:
After the fix:

fix: incorrect scaling of images in dialogImage

---

src/components/panels/ExtruderControlPanel.vue

This PR fix a bug in the condition to show the extra menu in the extruder panel. It only check the LOAD/UNLOAD_FILAMENT macro, but doesn't check the PURGE_FILAMENT or CLEAN_NOZZLE macro.
fixes #1744 
none
none

fix: show extruder extra menu without load/unload_filament macros

---

src/components/panels/GcodefilesPanel.vue
src/components/panels/Status/Gcodefiles.vue
src/plugins/webSocketClient.ts
src/store/files/actions.ts

Batch `server.files.metadata` requests to Moonraker, resulting in fewer re-renders of the file table (once per batch, rather than once per file). The performance improvement is especially noticeable with lists of 100+ files.
Moonraker has supported JSON-RPC Batch Requests for [at least 4 years](https://github.com/Arksine/moonraker/blame/96e69240caa3bc6b5a7be93f88ea90a0e8e38035/moonraker/websockets.py#L109), so I don't think backwards incompatibility is a concern.
An alternative approach could be to optimize the GCode Files table itself, which currently re-renders in its entirety when file metadata is updated. However, this approach felt more straightforward (and I'm not super familiar with Vue).
https://github.com/mainsail-crew/mainsail/assets/9659564/a6c279bf-5d7f-416a-847a-55fca8b63325 …

perf: batch gcode file metadata requests

---

src/components/CommandHelpModal.vue
src/components/panels/MiniconsolePanel.vue
src/pages/Console.vue

This PR will switch the color of the Command List or Console autocomplete from blue to primary.
fixes: #1730 
before:
after:
none

fix(console): fix color of autocomplete and command list

---

src/components/panels/JobqueuePanel.vue
src/components/panels/Status/Jobqueue.vue
src/components/panels/Status/JobqueueEntry.vue
src/components/panels/Status/JobqueueEntrySum.vue
src/locales/de.json
src/locales/en.json

This PR add a line on the bottom of the JobQueue panel with a sum of filamen, estimated printtime and an ETA.
fixes #1768 
none

feat: add sum + eta in jobqueue panel

---

src/components/TheTopbar.vue
src/components/gcodeviewer/Viewer.vue
src/components/panels/Machine/ConfigFilesPanel.vue
src/store/files/actions.ts

This PR fixes incorrect upload (and download in GCode viewer, although barely noticeable) rate being displayed as `NaN`, instead of an actual value.
Problem is caused by an incorrectly used `progressEvent` argument of Axios'es `onUploadProgress` callback, which exposes its own event object wrapper, instead the raw browser event (as I think someone has assumed, or maybe was the case in the past). Now, with Axios 1.x being used, `onUploadProgress` callback exposes `AxiosProgressEvent`-typed interface (this PR also corrects typings usage, instead of the nasty implicit `any`).
[`AxiosProgressEvent` "documentation"](https://github.com/axios/axios/blob/v1.6.0/index.d.ts#L287-L297) for reference (typings, their official documentation does not seem to describe the relevant interface).
Problem …

fix: file upload rate displays `NaN` instead of an actual value

---

src/components/dialogs/AddBatchToQueueDialog.vue
src/components/panels/GcodefilesPanel.vue
src/components/panels/HistoryListPanel.vue
src/components/panels/Status/Gcodefiles.vue
src/components/panels/Status/Jobqueue.vue
src/locales/en.json

This feature request & PR implements new context menu entry in History view, allowing users to add history entries to Queue. Right now, Mainsail only allows to start reprinting historical items immediately, which in certain cases might not be desired (eg. when user wants to print that file later; user is already printing something but wants to quickly schedule next prints from the History view; user wants to reprint a file, but with a different Spool which has to be changed via Spoolman panel on the Dasboard).
After adding an item to the Queue, a toast is being presented, indicating that something has happened. This was added mostly because adding to queue does not force any screen change (and it shouldn't, as there's no reason to do that, users might want to continue adding other …

feat: add ability to add history items to job queue

---

package-lock.json
package.json

Update @sindarius/gcodeviewer to latest after fix in upstream library.
First update (d34aa64) was to include OrcaSlicer in the supported slicers list; unfortunately it was including a bug where unlisted slicer features where aborting the rendering.
The new fix in the upstream library ensures that if supported slicers will add new features the render will continue to work and unsupported features will have a generic color instead of abort the render and throw an error.
#1752
https://github.com/Sindarius/npm_gcodeviewer/pull/13
https://github.com/Sindarius/npm_gcodeviewer/commit/be58ccea40f798b9662121dcdd78931cd901f879
No visual change
No

chore(deps): Update @sindarius/gcodeviewer (#1755)

---

src/components/panels/Machine/UpdatePanel/GitCommitsList.vue
src/components/panels/Machine/UpdatePanel/GitCommitsListDayCommit.vue

This PR just fix some UI issues in the commit list in the update manager. It add a min height on desktop devices and switch to fullscreen on mobile devices. on mobile devices i also changed the margin on the left side with the line and also put the hash of the commit at the bottom to have a single col layout inside of the commit.
none
before on desktop with less entries:
after on desktop with less entries:
before on mobile with less entries:
after on mobile with less entries:
after on mobile with more entries:

fix: fix commit list view on desktop and mobile devices

---

src/components/dialogs/SpoolmanChangeSpoolDialogRow.vue

Spoolman allows putting newline characters in the "Comment" field, allowing users to somewhat organize any notes relevant to certain spools (for example, I put the selling vendor name & what was the condition of the spool on arrival).
Currently, Mainsail does not preserve these newline characters, just renders the received comment "as-is" in a plain HTML fashion. This leads to everything being presented in one line, easily overflowing the table & dialog when a lot of notes are added. There's also no line break behavior defined, so even one-liner, long comments cause dialog overflow (see attached screenshot). 
However, `\n` character is nothing special when proper CSS is applied, so this can be easily fixed, which is what this PR does. It should also takes care of long, unbreakable words, …

fix(spoolman): break long comments & support multiline comments

---

src/components/panels/StatusPanel.vue

This PR fix long M117 outputs in the status panel.
none
before:
after:
none

fix: fix long M117 outputs in the status panel

---

src/components/inputs/MiscellaneousSlider.vue
src/store/printer/getters.ts

This PR will add the support from `pwm_tool` and `pwm_cycle_tool`. Both will displayed like a `output_pin`.
PRs in Klipper:
- https://github.com/Klipper3d/klipper/pull/6369
none
none

feat(miscellaneous): add support for pwm_tool and pwm_cycle_time

---

src/App.vue
src/assets/styles/page.css
src/routes/index.ts

This  PR adds a option in the routes to switch to fullscreen mode for single pages. It also changes the container size from G-Code Files, G-Code Viewer and Webcam page to fullscreen.
comment in an issue/FR: https://github.com/mainsail-crew/mainsail/issues/583
before:
after:
none

feat: add fullscreen size for gcodefiles, gcodeviewer and webcam

---

.github/workflows/release.yml

This PR fixes some deprecated warnings in the release workflow, but all actions are not available right now to fix all deprecate warnings.
Last run of the release workflow to check the warnings: https://github.com/mainsail-crew/mainsail/actions/runs/7922630451
none
none

ci: update actions in release workflow to fix node16 deprecates

---

src/components/panels/Machine/ConfigFilesPanel.vue

This PR add `*.bkp` files to the `Hide backup files` function in Config Files list.
fixes: #1794
none
none

fix: hide moonraker backups when "Hide backup files" is enabled

---

src/components/dialogs/CoolDownDialog.vue
src/components/panels/Temperature/TemperaturePanelPresets.vue
src/components/settings/SettingsUiSettingsTab.vue
src/locales/en.json
src/store/gui/index.ts
src/store/gui/types.ts

This PR adds the feature confirmation dialog to "COOLDOWN" button. (same looking dialog as the "Emergency Stop")
no issue number, too many times I clicked this button by mistake.
no

feat: Add confirmation dialog to cooldown button

---

src/components/panels/Machine/ConfigFilesPanel.vue

This PR only adds the regex to hide crowsnest backup files, when "Hide Backup files" is enabled in the Config Files panel.
none
none
none

fix: hide crowsnest backups when "Hide backup files" is enabled

---

src/components/mixins/zoffset.ts

This PR fix an issue with not visible "save" button for the z-offset.
none
none
none

fix: fix typo issues with save zoffset for probes

---

src/components/TheEditor.vue
src/store/editor/actions.ts
src/store/editor/mutations.ts

This PR remove the "Save & Close" button and adds a only "Save" button to the editor.
none
none
none

feat: add only save button to editor

---

src/components/mixins/base.ts
src/components/settings/SettingsUiSettingsTab.vue

This PR also allow "Printer" (with uppercase first char) as "printer power device", for the default setting.
fixes: #1812 
none
none

fix: fix case sensibility for printer power device

---

src/components/TheTopbar.vue
src/components/dialogs/EmergencyStopDialog.vue

This PR remove the fullscreen mode on mobile devices and add persistent funciton.
none
before:
after:
none

refactor(e-stop): remove fullscreen mode on mobile devices

---

src/App.vue
src/components/settings/SettingsUiSettingsTab.vue
src/locales/en.json
src/store/gui/index.ts
src/store/gui/types.ts

This PR adds a option to disable the progress circle as favicon during a print.
fixes: #1754 
none
none

feat: add option to disable favicon progress circle

---

.github/FUNDING.yml

Add the GitHub Sponsor link to the Mainsail Repo.
none
none
none

docs: add github sponsor link

---

src/components/panels/KlippyStatePanel.vue
src/locales/en.json

This PR is just a refactoring from the KlippyStatePanel for better readability.
none
none
none

refactor: refactor KlippyStatePanel

---

src/locales/en.json
src/store/gui/notifications/getters.ts
src/store/printer/types.ts

This PR add the support for Klipper Runtime Warnings. It only changes the headline from this notification warning.
- Klipper PR: https://github.com/Klipper3d/klipper/pull/6519
- publish the docs page:

feat: add support for klipper runtime warnings

---

src/components/webcams/streamers/WebrtcMediaMTX.vue

This PR fix the WebRTC webcam client for MediaMTX v1.2.1 and above.
none
none
none

fix: fix WebRTC(MediaMTX) webcam client

---

src/components/inputs/MacroButton.vue

This PR adds a tooltip to macro buttons which description is NOT the default (`G-Code macro`) macro description.
Fixes #1848

feat: show macro description as tooltip when hovering a macro

---

src/components/panels/Machine/LogfilesPanel/LogfilesPanelRolloverDialog.vue
src/components/settings/General/GeneralReset.vue
src/store/gui/actions.ts

This PR will ignore a wrong/not parseable default.json file during a moonraker db reset.
none
none
none

fix: ignore wrong default.json file while resetting moonraker db

---

package-lock.json
package.json
src/App.vue
src/components/TheTopbar.vue

This PR add the option to change the logo color, if you use SVG and add `var(--color-logo, #000000)` as fill color in the SVG file.
none
none
none

feat: expose css variable for changing theme logo color

---

src/store/server/history/getters.ts

This PR only remove an unused attribute in the getPrinttimeAvgArray history getter.
none
none
none

refactor: remove unused attribute in getPrinttimeAvgArray getter

---

src/components/inputs/MiscellaneousSlider.vue

With this PR we fixed the missing scale calculation caused by PR#[1804](https://github.com/mainsail-crew/mainsail/pull/1804).
The calculation is done after writing the gcode and then never updated. With this we always send the slider value between 0-1.
Fixes https://github.com/mainsail-crew/mainsail/issues/1869

fix: calc multiplicator for set_pin gcode

---

src/components/console/ConsoleTableEntry.vue

This PR fixes #1895 by adding `white-space: pre-wrap;`

fix: consecutive and leading whitespace is not shown in console

---

src/components/webcams/streamers/Mjpegstreamer.vue
src/components/webcams/streamers/MjpegstreamerAdaptive.vue

This PR fixes the contrast of the fps output in mjpegstreamer and mjpegstreamer-adaptive in the light theme.
fixes: #1900 
after: 
before:
none

fix(webcam): fix fps output in light mode

---

src/components/panels/Status/PrintstatusPrinting.vue

This PR fix the format function for durations (like total print time). This commit should fix round issues like `7:60` which should be `8:00`.
none
none
none

fix: fix duration format function

---

src/components/panels/Machine/SystemPanelHost.vue
src/store/server/getters.ts

This PR will remove an empty Temp output in the system loads panel.
none
Before:
After:
none

fix(systemLoads): fix temp output when no temp sensor was found in klipper

---

src/components/panels/StatusPanel.vue

This PR fix the "Pause at Layer" button in the Status panel. Until now, you saw this button, if you don't have "Exclude objects" active, set Layer counts, but no macros (SET_PAUSE_AT_LAYER & SET_PAUSE_NEXT_LAYER).
none
none
none

fix: display "pause on layer"-button only when the macros exists

---

package-lock.json
package.json
src/components/charts/TempChart.vue
src/store/printer/tempHistory/getters.ts

This PR fix the select/unselect function to hide/show monitor sensors in the tempchart.
Message from Aubey! on discord: https://discord.com/channels/758059413700345988/1248824088152244224
none
none

fix(tempchart): fix select/unselect monitor sensors in tempchart

---

src/components/dialogs/TheMacroPrompt.vue

This PR fix the computed showDialog in the macro prompts. I switch from array pos to timestamp from the event entry. The macro prompt didn't open, when you opened the same macro prompt multiple times without a refresh before.
fixes: #1899 
none
none

fix(macroPromts): fix internal close function

---

src/components/panels/Extruder/EstimatedExtrusionOutput.vue

This PR add the speed_factor to the estimate extrusion calculation and add a tooltip, when speed_factor and/or extrusion_factor is not 1.
fixes: #1904 
none

fix(extruderPanel): add speed_factor to estimate extrusion calc

---

src/components/panels/Status/PrintstatusThumbnail.vue

This PR fix the thumbnail overlay in the status panel with light mode. It change the overlay background color from black to white.
none
none

fix(statusPanel): fix the thumbnail overlay in the light theme

---

src/store/printer/getters.ts

This PR also add the firmware names for MCU, when it is different to Klipper (for example "Danger-Klipper").
PR in Danger-Klipper: https://github.com/DangerKlippers/danger-klipper/pull/301
none

feat(systemLoads): add firmware name, when it is not Klipper

---

src/components/panels/Status/PrintstatusThumbnail.vue
src/components/settings/SettingsUiSettingsTab.vue
src/locales/en.json
src/store/gui/index.ts
src/store/gui/types.ts

This PR adds an option to disable the thumbnail zoom effect in the status panel.
none
Interface Settings:

feat(statusPanel): add option to disable the thumbnail zoom

---

src/components/TheEditor.vue

I am trying to solve a personal issue of mine with this PR. I compulsively press <kbd>ctrl</kbd>+<kbd>s</kbd> while making changes in my editor, but this breaks my flow since it launches the save page dialog of the browser.
I propose overriding the default browser behavior for hotkeys with keybindings for our editor actions.
Changes:
- <kbd>ctrl</kbd>+<kbd>s</kbd> => Save
- <kbd>meta</kbd>+<kbd>s</kbd> => Save (Mac)
- <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>s</kbd> => Save + Restart 
- <kbd>meta</kbd>+<kbd>shift</kbd>+<kbd>s</kbd> => Save + Restart (Mac)
I could try and make a screen recording of pressing the hotkeys but I didn't feel like it would add much to the PR

feat: Add hotkeys tied to Save, Save + Restart

---

src/components/dialogs/TheScrewsTiltAdjustDialog.vue

This PR fixes an issue with the `SCREWS_TILT_CALCULATE` helper panel. It checks the console history for the last execution of the `SCREWS_TILT_CALCULATE` command to use the same `DIRECTION` as the initial command.
fixes: #1917 
none
none

fix(screwsTiltCalculate): use the same direction on retry

---

src/components/panels/Machine/UpdatePanel/Entry.vue

This PR fix the logic from the update button in the update_manger for git_repos without semver versioning.
none
none
none

fix(updateManager): fix updatr for git_repos without semver

---

public/img/themes/sidebarLogo-voron.svg
src/store/variables.ts

This PR adds a Voron Design theme (just logo and logo color).
none
none

feat(theme): add voron build-in theme

---

src/components/settings/SettingsUiSettingsTab.vue

This PR fix the color change if you change the theme with different default colors.
none
none
none

fix(theme): fix color change on theme change

---

src/store/gui/maintenance/getters.ts

This PR fix the filament trigger for maintenance entries. The factor for converting mm to m was missing in the getter.
fixes #1938 
none
none

fix(maintenance): fix filament trigger for maintenance entries

---

src/store/gcodeviewer/mutations.ts

This PR fixes a performance issue when leaving the G-Code Preview page. 
To reproduce:
- Load a 3d preview from the file view. Wait for it to render.
- Attempt to navigate away and observe the browser hanging for several seconds.
For whatever reason, my Firefox started choking on this recently. Chrome at least recovered so I could get a profile :smiley:

perf: fix hang when leaving G-Code Preview page

---

src/components/gcodeviewer/Viewer.vue

This PR fix the simulation function in the gcodeviewer while printing. It blocks the live nozzle position and fileposition updates when tracking is disabled.
Commit in an old bug report: https://github.com/mainsail-crew/mainsail/issues/1924#issuecomment-2241256820
none
none

fix(gcodeviewer): fix gcodeviewer simulation while printing

---

public/css/themes/vzbot.css
src/App.vue
src/components/mixins/theme.ts
src/store/types.ts
src/store/variables.ts

This PR adds an option to load an optional CSS file per theme. To enable this theme file, you have to add the attribute `css: true` to the theme settings and add a CSS file in `/public/css/themes/<themeName>.css`. This file will be fetched and added to the header.
none
none
none

feat(theme): add option for dedicated CSS file per theme

---

src/components/panels/Machine/UpdatePanel/Entry.vue

Use the `desc` in `info_tags` from the `update_manager` section in the `moonraker.conf`. This is a config example:
```
[update_manager beacon]
type: git_repo
channel: dev
path: ~/beacon_klipper
origin: https://github.com/beacon3d/beacon_klipper.git
env: ~/klippy-env/bin/python
requirements: requirements.txt
install_script: install.sh
is_system_service: False
managed_services: klipper
info_tags:
desc=Beacon Surface Scanner
```
none
With this PR:
none

feat(updateManager): use info_tag desc for the name

---

src/plugins/helpers.ts

This PR fix an issue with a space as a first letter in console output.
none
before:
after:
none

fix(console): trim output to remove spaces at first char

---

src/components/webcams/streamers/WebrtcMediaMTX.vue

This PR fix the UUID request in the MediaMTX webcam client and refactor some code.
none
none
none

fix: fix uuid request in MediaMTX webcam client

---

src/components/console/ConsoleTableEntry.vue
src/plugins/helpers.ts
src/store/server/actions.ts
src/store/server/mutations.ts

This PR implements a `// debug:` prefix for console messages that will have them displayed as greyed out. The implementation is based on the discussion had in #1950.
Closes #1950.
Should this be mentioned in the docs? If so, where?
Examples generated with the following macro (`RESPOND TYPE="command" MSG="debug: hello world"` could have also been used):
```plaintext
[gcode_macro _LOG]
gcode:
{action_respond_info("%s%s" % ("debug: " if params.DEBUG|default(0)|int == 1 else "", params.T))}
```
Before:
After:
N/A

feat(console): add debug prefix

---

src/components/panels/WebcamPanel.vue
src/components/settings/Webcams/WebcamForm.vue
src/components/webcams/WebcamWrapper.vue
src/components/webcams/WebcamWrapperItem.vue
src/components/webcams/streamers/WebrtcMediaMTX.vue
src/pages/Webcam.vue

This PR fix these WebRTC connection issues:
- double connections
- terminate session when backend is not available
- start/stop when open/close panel on the dashboard
- start stream in webcam page, when dashboard panel is closed
none
none
none

fix(MediaMTX): fix some connection issues

---

src/components/console/ConsoleTableEntry.vue
src/components/panels/MiniconsolePanel.vue
src/locales/en.json
src/pages/Console.vue
src/store/gui/console/index.ts
src/store/gui/console/types.ts

This PR adds an option to display all console outputs without filtering prefixes or something similar. This could help to create better filter regex rules, because you see prefixes like `//` or `!!`.
I came up with this idea during a conversation in the Mainsail Discord: https://discord.com/channels/758059413700345988/1273211754423521323
without raw-output:
with raw-output:

feat(console): add option for RAW-output (for debugging)

---

src/components/panels/Extruder/ExtruderControlPanelControl.vue

This PR restores the gcode state to the state before the extrusion, triggered through the UI, happenend.
The old behavior changes the extrusion mode and can create problems with absolute extrusion setups.
The new behavior saves the state with `SAVE_GCODE_STATE` an unique name and restores this state with `RESTORE_GCODE_STATE` after the extrusion happened.
This extends on the idea of #1964 but uses only Klipper built in commands to make this more generic.
none
none

fix(ExtruderPanel): restore mode after extruding/retracting

---

src/components/dialogs/TimelapseRenderingsettingsDialog.vue
src/components/mixins/timelapse.ts
src/components/panels/Timelapse/TimelapseStatusPanel.vue

This PR refactor the complete TimelapseStatusPanel and fix the issue with flip/rotate settings, when snapshoturl is set in the moonraker.conf.
none
none
none

refactor(timelapse): refactor the timelapse status panel

---

src/components/panels/Extruder/ExtruderControlPanelControl.vue

This PR combine the sendRetract & sendExtrude function and add a `_` as prefix to the gcode_state.
Suggestion from @pedrolamas in the control panel PR: https://github.com/mainsail-crew/mainsail/pull/1988#discussion_r1741707530
none
none

refactor(ExtruderPanel): add `_` prefix to gcode_state name

---

src/components/TheConnectingDialog.vue
src/locales/en.json
src/plugins/webSocketClient.ts
src/store/socket/actions.ts
src/store/socket/index.ts
src/store/socket/mutations.ts
src/store/socket/types.ts

This PR adds an output for "Unauthorized" connections on the ConnectionDialog. Without this PR, the user would only see an endless initialize dialog.
fixes #1971 
before:
after:
none

feat: add output on connection dialog for unauthorized

---

src/components/webcams/streamers/MjpegstreamerAdaptive.vue
src/locales/en.json

This PR refactor the Mjpegstreamer-Adaptive webcam mode for more performance and simplify code.
none
none
none

refactor(webcam): refactor Mjpegstreamer-Adaptive Webcam mode

---

src/components/webcams/WebcamWrapperItem.vue
src/components/webcams/streamers/Mjpegstreamer.vue
src/locales/en.json

This PR fixes a memory leak in the Mjpeg-Streamer client with Firefox.
fixes: #904 
none
none

fix(webcam): fix memory leak in MJPEGStreamer client

---

src/components/panels/Machine/UpdatePanel/GitCommitsList.vue

Fixes an incorrect GitHub URL when the Moonraker `update_manager` extension name does not match the GitHub repo name.
Given the following update manager extension config ([which is the one LED Effects for Klipper uses](https://github.com/julianschill/klipper-led_effect/blob/master/file_templates/moonraker_update.txt))
```ini
[update_manager led_effect]
type: git_repo
path: ~/klipper-led_effect
origin: https://github.com/julianschill/klipper-led_effect.git
is_system_service: False
```
The change corrects the "Link to GitHub" buttton's address from
https://github.com/julianschill/led_effect/commits/master/?after=bde44b49246a0fe7b50d41e415d71e8f966d9542+0
to
https://github.com/julianschill/klipper-led_effect/commits/master/?after=bde44b49246a0fe7b50d41e415d71e8f966d9542+0
none
none
none

fix: correct github commit after link in commit list

---

src/plugins/webSocketClient.ts

This PR adds a heartbeat function to the Websocket and disconnect, when no ping arrive from Moonraker for more than 10 seconds.
fixes #1536 
none
none

feat: add heartbeat to the moonraker websocket

---

src/components/panels/Extruder/EstimatedExtrusionOutput.vue

This PR fix the percent output in the tooltip from the estimated extrusion output.
none
before:
after:
none

fix(ExtruderPanel): fix extrude and speed factor output

---

src/components/TheEditor.vue

- Fixes jarring editor experience as described in #2011
- It uses a flag to indicate when sidebar item activation originates from the sidebar itself, or somewhere else, by detecting the sidebar's item click. Not a perfect solution, but generally works, although it does leave a bit of a dead click zone when user clicks on very boundaries of sidebar's item. Still better than previous behavior.
- Once Mainsail upgrades to Vuetify v3, this can be solved a bit easier & cleaner using `click:open` event handler of the Treeview component, see https://vuetifyjs.com/en/api/v-treeview/#events-click:open
- Fixes JS error being thrown when sidebar item is deactivated by "unclicking" the item
- Also, slightly improves TS typings for `activeChanges`, although due to `this.editor` being typed as `any`, …

fix(Editor): Trigger gotoLine only when change is from sidebar

---

src/components/panels/History/HistoryListEntryJob.vue

Fixes missing thumbnails in History page for files placed in non-root folders.
Bonus: refactors thumbnails url generation code so that it is reused for both small & big thumbnails, and improves TypeScript coverage by eliminating unwanted `any` usage.
#2009

fix(HistoryPanel): Fix History thumbnails of files in folders

---

src/plugins/webSocketClient.ts
src/store/server/actions.ts

This PR only implement a function to the WebsocketClient to send a request and wait for the response. Thx @Spice-King for this implementation/syntax.
none
none
none

chore(websocket): add function to send and wait for response

---

src/components/charts/HeightmapChart.vue
src/components/settings/SettingsHeightmapTab.vue
src/locales/en.json
src/store/gui/heightmap/index.ts
src/store/gui/heightmap/types.ts

This PR adds an option in the Settings to let the user set the default orientation of the bed mesh visualization.
fixes #993 
Option "Right Front" (default option and the same orientation as before):
Option "Left Front":
Option "Front":
Option "Top":
none

feat(Heightmap): add option to set the default orientation

---

src/components/TheConnectingDialog.vue
src/locales/de.json
src/locales/en.json

This PR adds a "Help" button to the Connection Dialog, when the Connection error is "Unauthorized".
fixes #2026 
Link to the Docs: https://docs.mainsail.xyz/faq/mainsail_errors/connection-unauthorized
none

feat: Add link to the Docs for Unauthorized connections

---

.docker/nginx.conf

I'm having connectivity issues in my dual stack environment and this seems to fixes them.

chore(Docker): Enable ipv6 in nginx.conf

---

src/components/panels/Extruder/ExtruderControlPanelTools.vue

This uses a formula to make the tool rows have or at least approximately have even lengths. The current behaviour is the last row has `num % 6` tools. There will be no more rows than there was before.
none
Before:
After:
none

fix: Tool rows in even lengths, and more visually tidy

---

src/components/TheEditor.vue

This PR just fix the Klipper Reference button in the editor topbar and the sidebar with the section while printing.
none
none
none

fix: fix reference link in editor while printing

---

src/components/panels/Machine/SystemPanel.vue

This PR adds a button to open the DeviceDialog in the SystemPanel in the Machine page.
fixes #2044 
none

feat: add button to open the device dialog in SystemPanel

---

src/components/webcams/streamers/Mjpegstreamer.vue
src/components/webcams/streamers/MjpegstreamerAdaptive.vue
src/components/webcams/streamers/Uv4lMjpeg.vue

This PR makes the `<img>` tags created by the webcam preview non-draggable. They were draggable before, which would (at least in my case) lead to accidentally dragging it and uploading it to the config folder using the drag and drop function.
I was only able to test the `Mjpegstreamer` and `MjpegstreamerAdaptive`, so I didn't modify any of the other views.

fix(Webcam): make webcam view non-draggable

---

src/components/mixins/zoffset.ts

This PR fix the save z offset function in the toolhead panel. It looks like i broke it in this PR #2033 
none
none
none

fix: fix save z offset in toolhead panel

---

src/components/dialogs/TheMacroPrompt.vue

Previously we were only looking for a series of prompt action events within the last 100 events. However, if things are happening in the background while the prompt is still open, those events can keep racking up and eventually the prompt window will close (though klipperscreen still displays it).
I've now refactored this code so that it will internally keep an array of the prompt events and we will process through all the events at first, but we will set a checkpoint at the most recent processed event so that we don't go back and re-process ones that were already done. Effectively this means on first load sure we iterated through potentially a lot of events, but then after that we're really only processing through at most a few events. It is certainly less concise than the previous …

fix: keep macro prompt open for events older than 100

---

src/components/mixins/control.ts
src/components/panels/Extruder/ExtruderControlPanelControl.vue
src/components/panels/ToolheadControls/MoveToControl.vue

This PR use will change the move gcodes, when _CLIENT_AXIS_MOVE or _CLIENT_EXTRUDER_MOVE macros exists. This will make the console less noisy.
PR: mainsail-cew/mainsail-config
none
none

feat: use _CLIENT_LINEAR_MOVE macros instead of multi-line gcodes

---

src/components/gcodeviewer/Viewer.vue
src/components/panels/GcodefilesPanel.vue
src/components/panels/History/HistoryListEntryJob.vue
src/components/panels/Machine/ConfigFilesPanel.vue
src/components/panels/Status/GcodefilesEntry.vue
src/components/panels/Status/HistoryEntry.vue
src/components/panels/Status/PrintstatusThumbnail.vue
src/components/panels/Timelapse/TimelapseFilesPanel.vue
src/plugins/helpers.ts
src/store/editor/actions.ts
src/store/files/getters.ts
src/store/server/jobQueue/getters.ts

This PR escape all thumbnail and file URLs to fix issues with special chars like `#` and more. This is necessary because Klipper supports Gcodes with it after this PR: https://github.com/Klipper3d/klipper/pull/6749
none
none
none

fix: escape all file URLs to support all kind of special chars

---

src/components/webcams/streamers/WebrtcCameraStreamer.vue

This PR adds a check for ICE Candidates to fix the connection to older camera-streamer backends (for example the default version for the latest MainsailOS v1.3.2).
fixes #2068 
none
none

fix(Webcam): add ICE check to support older CS versions

---

src/components/mixins/zoffset.ts
src/components/settings/SettingsControlTab.vue

This PR fix the Control-Tab in the Interface-Settings when the printer/Klipper is not ready.
none
none
none

fix: fix interface settings Control-Tab when printer is not available

---

src/components/panels/Status/GcodefilesEntry.vue

This PR will fix the issue with start prints form the dashboard with files in a subdirectory. It creates a new file object without the complete path as filename for the start-print-dialog.
fixes #2073 
none
none

fix: fix print start from dashboard for subdirectory files

---

src/components/dialogs/TheMacroPrompt.vue

Previously if you had a macro prompt such as the following, the modal title would display `Question`, not `"Question"`. However, in other projects (Klipperscreen and Fluidd), they will preserve those outer quotes and they will be included in the title. This change makes Mainsail consistent with the other implementations.
```
RESPOND TYPE=command MSG="action:prompt_begin \"Question\""
RESPOND TYPE=command MSG="action:prompt_button Button1|RESPOND MSG=\"Clicked it!\""
RESPOND TYPE=command MSG="action:prompt_show"
```
Implements discussion from #2045.

fix(macro-prompts): preserve outer quotes

---

src/components/TheEditor.vue

This PR fixes the maximal height of the editor sidebar. When you have too many entries, it will add a scrollbar in this sidebar, instead of scrolling the complete editor fullscreen dialog.
fixes #2077 
none
none

fix(Editor): fix maximal height of the sidebar

---

src/components/dialogs/StartPrintDialog.vue

This PR hide the horizontal scrollbar in the StartPrintDialog, but the vertical scrollbar is still untouched and can be visible, when the window is too small.
none
before:
after:
none

fix: hide horizontal scrollbar in StartPrintDialog.vue

---

src/components/mixins/control.ts
src/store/printer/getters.ts

This PR fix fix the z_tilt button for z_tilt_ng when using Kalico. I just changed the check from checking the config for a z_tilt section to just check if the gcode Z_TILT_ADJUST exists.
fixes #2067 
none
none

fix: fix z_tilt button for z_tilt_ng with Kalico

---

src/components/mixins/control.ts
src/components/panels/Extruder/ExtruderControlPanelTools.vue
src/components/panels/Extruder/ExtruderControlPanelToolsItem.vue
src/store/printer/types.ts

This PR fix the issue when hardcoded gcodes are used instead of gcode_macros for tool macros.
none
none
none

fix(Tools): use gcode commands instead of config gcode macros

---

src/components/settings/SettingsControlTab.vue
src/locales/en.json

This PR adds a missing translation key in the SettingsControlTab for "Overwrite action button".
fixes #2101 
none
none

fix(Locale): Add missing translation key in SettingsControlTab

---

src/components/inputs/ConsoleTextarea.vue

This PR improves the key up/down function in the console history to scroll/jump multiline inputs up/down instead of jumping for/back in the history.
fixes #609 
https://github.com/user-attachments/assets/9a630067-142c-42c5-8a00-d0d8c463b2b3
none

feat(Console): Improve key up/down function in Console textarea

---

package-lock.json
package.json

This PR update the gcode-viewer lib to fix G2/G3 visualisation.
fixes: #2123 
none

fix: update Gcode-Viewer lib from sindarius to fix G2/G3 visualisation

---

src/components/panels/Machine/UpdatePanel/Entry.vue
src/store/server/updateManager/actions.ts
src/store/server/updateManager/types.ts

This PR adds support for python applications, see [Moonraker Python Application](https://moonraker.readthedocs.io/en/latest/configuration/#python-application-configuration)
[Discord Thread](https://discord.com/channels/758059413700345988/1318668410321764362)
```conf
[update_manager python_test]
type: python
channel: dev
virtualenv: ~/klippy-env
project_name: cartographer
is_system_service: False
managed_services: klipper
info_tags: desc=Python Test
```
You will have to do the initial install with `~/klippy-env/bin/pip install git+https://github.com/Jomik/cartographer-scanner-klippy.git`
To uninstall `~/klippy-env/bin/pip uninstall cartographer`
No

feat(Update): implement python package entries

---

src/components/panels/HistoryListPanel.vue

This PR fix the "count per page" switch in the History List Panel.
none
none
none

fix(History): fix count per page switch in the History List Panel

---

src/components/panels/Timelapse/TimelapseFilesPanel.vue

This PR fix the "count per page" select in the Timelapse Files Panel.
none
none
none

fix(Timelapse): fix count per page switch in the Timelapse Files Panel

---

src/components/TheEditor.vue
src/store/gui/index.ts
src/store/gui/types.ts

This PR add a function to store the last state of file structure sidebar in the Editor.
none
none
none

feat(Editor): store last state of file structure sidebar

---

src/components/mixins/control.ts
src/store/printer/getters.ts

This PR fix the z_tilt check and add a fallback for older Klipper versions in the control mixin.
fixes #2100 
none
none

fix(z-tilt): Fix z_tilt check for older Klipper versions

---

src/components/panels/Machine/SystemPanel.vue

This PR fix the issue with "not showing System Panel", when Klipper is not ready. 
fixes: #2147 
none
none

fix: show system panel when klipper is not ready

---

src/components/panels/Temperature/TemperaturePanelListItem.vue
src/locales/en.json
src/plugins/eventBus.ts

This PR adds a ContextMenu to each entry in the Temperature Panel to open the Settings dialog and for heaters add an option to turn of this specific heater.
none
If heater has a target temp:
If heater has 0 as target temp:
If the line is no heater:
none

feat(Temperatures): add menu to open Settings & turn off heaters

---

src/components/panels/Machine/EndstopPanel.vue
src/components/panels/Machine/EndstopPanelItem.vue

This PR refactor the complete Endstop Panel in the Machine Page and add support for the dockable_probe (Kalico).
none
none
none

refactor(Machine): refactor endstop panel and add dockable_probe

---

src/components/dialogs/SpoolmanChangeSpoolDialog.vue

Fixes an issue with saving spool IDs for individual tools on a multi-tool instance. Currently, no updates are written to the variables file and an error is shown when selcting a new spool for any toolhead. The cause appears to be that upper case letters (which the current implementation uses) are not allowed. See the [Klipper docs](https://www.klipper3d.org/G-Codes.html#save_variable).
This PR simply changes the variable name to lower case, resolving the problem.
Running Klipper v0.12.0-451, Moonraker v0.9.3-65
n/a
Console output displaying the error message:
n/a
Signed-off-by: Paul Gendolla <contact@gendolla.net>

fix(spoolman): save spool id in lowercase variable

---

src/components/panels/Miscellaneous/MiscellaneousSensor.vue
src/components/panels/Miscellaneous/MoonrakerSensorValue.vue
src/components/panels/MiscellaneousPanel.vue
src/plugins/helpers.ts
src/store/printer/getters.ts
src/store/printer/types.ts

This adds a new general purpose `MiscellaneousSensor`, with support for only load_cell gram scales. This is just a simple single line entry in the MiscellaneousPanel, with a getter to extract the value from the printer state.
With an uncalibrated load cell:
After calibration:

feat: Add load cell gram scales in misc panel

---

src/components/inputs/FilamentSensor.vue
src/components/panels/MiscellaneousPanel.vue
src/store/printer/getters.ts
src/store/printer/types.ts

The hall_filamend_width_sensor includes a filament runout sensor in Klipper, and the filament runout sensor part is exposed in the API since Klipper3d/klipper#6861. This extends the existing filament sensor functionality of Mainsail to include filament width sensor functionality.
In the UI, the difference between a plain runout sensor and a filament width sensor is that for a filament width sensor the filament width will be shown instead of just the string "detected".
Empty:
With filament inserted:

feat: Add support for hall filament width sensor

---

package-lock.json
package.json

This PR just remove the deprecated package `@types/cypress`. This is already included in the cypress package.
More infos about it here: https://www.npmjs.com/package/@types/cypress
none
none

chore: remove deprecated @types/cypress package

---

.github/workflows/auto-analyze.yml

This PR change back to the GITHUB_TOKEN in the auto-analyze.yml.
none
none
none

ci: use GITHUB_TOKEN in auto-analyze.yml

---

.github/workflows/check_locale.yml
.gitignore
package.json
vue-i18n-extract.config.js

This PR fix the workflow "check_locale". This was broken until i uploaded all dependencies (#2168). It looks like a bug in the current vue-i18n-extract package with the glob dependencies.
I removed the "use-config" attribute and use the config inline, which is a workaround for the current issue in vue-i18n-extract package.
- issue in vue-i18n-extract repo: https://github.com/Spittal/vue-i18n-extract/issues/159
- happy hair PR which failed with the current workflow: https://github.com/mainsail-crew/mainsail/pull/2158
none
none

ci(check-locale): fix issues with i18n-extract workflow

---

.github/workflows/check_locale.yml

This PR fix the path to the vue-i18n-extract script, because this script will not be installed global.
none
none
none

ci(check-locale): fix path to vue-i18n-extract script

---

package-lock.json
package.json

This PR fix Scarf Seams in the Gcodeviewer by bump `@sindarius/gcodeviewer` package to 3.7.17. Thx @Sindarius for fixing this bug!
fixes #2219 
none
none

fix(gcodeviewer): fix scarf seams in Gcodeviewer

---

src/store/files/actions.ts
src/store/files/getters.ts

This PR fix the disk usage in the file manager panel, when you create a new directory and open it directly after that.
fixes #2214 
none
none

fix(Files): fix disk usage in new directories

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

This PR change from labels to types in the issue tracker for new bugfixes and feature requests.
- Blogpost: https://github.blog/changelog/2025-01-12-evolving-github-issues-public-preview/#%f0%9f%93%81-organize-your-work-with-issue-types
- Public preview: https://github.com/orgs/community/discussions/148715
none
none

chore: update ISSUE_TEMPLATEs zu use the type field

---

.github/workflows/publish_docker.yml
Dockerfile

This makes the image compliant with the restricted pod security standard:
https://kubernetes.io/docs/concepts/security/pod-security-standards/
There is major difference to the current image in that it now listens on port 8080 since ports below 1024 can only be opened by privileged users. I don't really know how to proceed with this.
Is this something that can be released with a note in the releasenotes and an update to the docs? Or I could setup a separate image which uses a `-unprivileged` postfix on the tags and keep the current image the same.
Or update the current image but setup a `-privileged` postfix with the root running image as a legacy option?
Besides that this is a good security practice, this enabled this image to run in more restricted environments where the pod security …

feat: add -unprivileged docker image to conform with restrired pod security standard

---

src/components/mixins/webcam.ts
src/components/webcams/streamers/MjpegstreamerAdaptive.vue

This PR fix the issue with too big image, when you rotate a portrait stream 90° or 270°. It also simplify the generateTransform function in the webcam mixin.
fixes #2156 
none
none

fix(Webcam): fix portrait webcam rotation in mjpegstreamer-adaptive

---

src/components/dialogs/AfcSettingsDialogExtruder.vue

This PR fix an issue with "too many" lanes in the AFC-Settings pane. I added a div with "flex-wrap" so it can break the line when more lanes are added.
none
old:
new:
none

fix(AFC): this PR fix the AFC settings with many lanes
