- README.md
This is a PR that tweaks some of the README that fixes some of the typos. I did not go much into detail.
> Few tweaks to the README file

- src/components/panels/Settings/ConfigFilesPanel.vue
- src/components/panels/StatusPanel.vue
> Separated some words

- src/store/getters.js
- factor out sort into a named function and share it among common
callers
- ~~add a suggested .editorconfig to avoid changing indents and line endings~~
- ~~add a suggested .pretterrc which honors original formatting as much
as possible~~
~~Apologies for formatting changes, these are done automatically by the tooling. Let me know if you want them gone. I generally don't format code by hand anymore and just let prettier take care of it on save.~~
> Share the sort function in getters between functions

- src/store/mutations.js
Adds small helper function, to avoid repeating pattern.
> Small helper function for DRY code

- src/App.vue
Added benefit of the emergency stop button being always available.
> feature: ensures app bar doesn't scroll off page

- docs/setup-guide/manual-setup/moonraker.md
new updatemanager config style in manual setup
Signed-off-by:  Christoph Frei <fryakatkop@gmail.com>
> docs: update manager config in manual setup

- docs/_sass/color_schemes/mainsail.scss
add styles for 
success (green), info (blue), warning (orange), alert (red) messages.
> docs: add different message styles

- src/components/panels/MiscellaneousPanel.vue
- src/components/panels/ToolsPanel.vue
- src/inputs/MiscellaneousSlider.vue
- src/store/printer/getters.js
> feature: add rpm to miscellaneous fans and temperature_fans

- docs/necessary-cfg.md
Change macros in preparation of the removal of default_parameter
Signed-off-by: Alex Zellner alexander.zellner@googlemail.com
> remove defaut_parameter from macro

- docs/themes/backgrounds.md
https://github.com/meteyou/mainsail/commit/9f2a54100b2c43f8c4a7f5f370e63029cdc37dc8
> docs: add .svg as valid background extension

- src/components/webcams/MjpegstreamerAdaptive.vue
> featere: switch mjpegstreamer to canvas

- docs/_data/themes.csv
- docs/_layouts/themes.html
- docs/_sass/color_schemes/mainsail.scss
- docs/assets/js/images.js
- docs/themes/themes.md
Add voron toolhead and cyperpunk communtiy themes and a few improvements of how screenshots get loaded.
Special thanks to @eriroh (Voron) and @Dario-Ciceri (Cyperpunk). 
Their themes can be found here: https://docs.mainsail.xyz/theming/themes
> docs: add communtiy themes and improvements of loading screenshots

- src/components/ConsoleTable.vue
- src/components/panels/MiniconsolePanel.vue
- src/pages/Console.vue
- src/plugins/helpers.ts
- src/store/printer/types.ts
- src/store/server/mutations.ts
added linux like autocompletion
multi line gcode
gui helplist with search
clickable recent commands
> Console QOL

- docs/necessary-cfg.md
Update CANCEL_PRINT following the discussion in klipper PR#4366 and change the exruder check from temperature to the status added by  klipper PR #4366
Signed-off-by: Alex Zellner <alexander.zellner@googlemail.com>
> update macros because of klipper PR #4366 and PR #4362

- docs/setup-guide/mainsail-os.md
Improved Formatting
Signed-off-by: Stephan Wendel <me@stephanwe.de>
> Fixed Ordered Lists and Improved Formatting

- docs/setup-guide/mainsail-os.md
Thanks to mysfiring from Mainsail Discord.
Only to avoid confusion about usable Platforms.
Signed-off-by: Stephan Wendel <me@stephanwe.de>
> Added Multiplatform Hint

- docs/development/standalone.md
change preferred way of installing node to nvm
> docs: added nvm node install for standalone dev env

- src/components/panels/ControlPanel.vue
- src/components/panels/FarmPrinterPanel.vue
- src/locales/en.json
- src/store/farm/printer/getters.ts
- src/store/farm/printer/mutations.ts
fix display and reconnect of farm printer panel
> hotfix: printerfarm panel

- src/components/mixins/base.ts
- src/components/webcams/Mjpegstreamer.vue
- src/components/webcams/MjpegstreamerAdaptive.vue
- src/components/webcams/Uv4lMjpeg.vue
- src/store/socket/getters.ts
relative webcam url dont work for remote printers
> hotfix: display right webcam from remote printer

- src/pages/Files.vue
> hotfix: fix typo gcodefiles

- src/App.vue
- src/store/files/getters.ts
> hotfix(theme): fix mainBackground image #349

- package-lock.json
- package.json
- src/App.vue
- src/components/CommandHelpModal.vue
- src/components/TheEditor.vue
- src/components/TheSettingsMenu.vue
- src/components/TheUpdateDialog.vue
- src/components/gcodeviewer/Viewer.vue
- src/components/inputs/Codemirror.vue
- src/components/panels/HistoryListPanel.vue
- src/components/panels/Machine/ConfigFilesPanel.vue
- src/components/panels/Machine/SystemPanel.vue
- src/components/panels/Machine/UpdatePanel.vue
- src/components/panels/MiniconsolePanel.vue
- src/components/settings/SettingsControlTab.vue
- src/components/ui/Panel.vue
- src/main.ts
- src/pages/Console.vue
perfect-scrollbar have issues with touch devices
> feat: change overlaps-scrollbar instead of perfect-scrollbar

- src/components/settings/SettingsWebcamsTab.vue
- src/components/webcams/Mjpegstreamer.vue
- src/store/server/timelapse/mutations.ts
cancel streams by change page or the webcam panel is not in the viewport
> fix: webcam mjpegstreamer mode

- src/components/inputs/MiscellaneousSlider.vue
- src/components/inputs/ToolSlider.vue
- src/components/panels/MiscellaneousPanel.vue
- src/components/panels/PrintsettingsPanel.vue
- src/store/gui/actions.ts
- src/store/gui/index.ts
* prevent unnecessary moonraker db traffic
* display lock icon only on correct elements
> fix: patch slider lock feature

- src/locales/es.json
V2.1.0-beta2 Spanish Translation / V2.1.0-beta2 Traduccion al español
> V2.1.0-beta2 Spanish Translation

- src/components/panels/MachineSettings/FirmwareRetractionSettings.vue
- src/components/panels/MachineSettings/MotionSettings.vue
* full width per input on smaller devices
> fix: input layout on small devices

- src/components/inputs/ToolSlider.vue
- src/components/panels/PrintsettingsPanel.vue
adding icons for the print settings.
> fix: add icons for print settings

- src/components/webcams/Mjpegstreamer.vue
> fix: cancel open connection before close fetch of mjpegstreamer webcam

- src/components/panels/MiniconsolePanel.vue
- src/locales/en.json
- src/pages/Console.vue
- src/store/gui/consolefilters/getters.ts
- src/store/gui/index.ts
> feat: add option to hide TL gcodes in console

- package-lock.json
- package.json
> chore: update vuetify package

- src/components/panels/MiniconsolePanel.vue
- src/components/settings/SettingsGeneralTab.vue
- src/locales/en.json
- src/pages/Console.vue
- src/store/gui/gcodehistory/actions.ts
- src/store/gui/gcodehistory/getters.ts
- src/store/gui/gcodehistory/index.ts
- src/store/gui/gcodehistory/mutations.ts
- src/store/gui/gcodehistory/types.ts
- src/store/gui/index.ts
- src/store/server/actions.ts
- src/store/server/mutations.ts
- src/store/variables.ts
to save the console history beyond the session
> feat: store last gcode commands in moonraker db

- src/components/panels/MachineSettings/PressureAdvanceSettings.vue
> fix: prevent duplicates

- src/store/server/timelapse/actions.ts
> bugfix: display moonraker-timelapse error message

- src/locales/de.json
> locale: update de translation

- src/components/TheSidebar.vue
sidebar overlay had an condition which caused some strange behaviour.
removed it.
Signed-off-by: steadyjaw <martin.keilaus@gmail.com>
> fix: remove buggy condition for sidebar overlay

- src/components/TheTopCornerMenu.vue
- src/locales/de.json
- src/locales/en.json
* refactor: confirmation dialog visuals, change button color to red, replace titlebar icon
* fix: add klipper service restart condition
* i18n: improve wording of en and de translations
> refactor: improve confirmation dialog visuals

- src/components/TheSidebar.vue
- src/components/TheTopbar.vue
* fix visibility of sidebar logo when in icons only mode
* fix: increase z-index of topbar when in specific display breakpoints, so that it sity above the overlay of the sidebar
> fix: sidebar logo and topbar-sidebar overlay

- src/components/ui/Panel.vue
> refactor: change panel expansion indicator

- src/components/settings/SettingsControlTab.vue
- src/locales/de.json
- src/locales/en.json
* fix input validation of input field and combo-boxes
* move warnings to locales
* omit duplicate entries in combo-boxes
> Fix: control settings

- src/locales/hu.json
> locale(hu): hun update 20220110 as requested :)

- src/locales/hu.json
> locale(hu): 2022 01 12 update

- src/pages/Heightmap.vue
```
* fix: remove text-transformation on rename-button
* fix: remove toUpperCase on renameProfile
* fix: add remove command to renameProfile
```
> Heightmap: fix capitalization of names and renaming functions  (fix #545,#546)

- src/components/inputs/MacroButton.vue
> feat: send gcode macro with keyup enter

- src/locales/ru.json
Please check if the missing values are all present @meteyou
> locale(ru): Update RU v2.1

- docs/themes/prepare.md
Fix the paragraph on preparing the custom theme with lixxbox's feedback (thanks!)
> docs: Update prepare themes page with review feedback

- src/components/gcodeviewer/Viewer.vue
> fix: read nozzle_diameter from klipper config in gcodeviewer

- src/components/inputs/FirmwareRetractionSettingsInput.vue
- src/components/inputs/MotionSettingsInput.vue
- src/components/inputs/PressureAdvanceSettingsInput.vue
- src/components/panels/MachineSettings/PressureAdvanceSettings.vue
* fix: reset unconfirmed input on blur (fixes #551)
* fix: remove pressure advance upper limit
> fix: input field and spinner bug (fixes #551)

- src/store/files/actions.ts
> fix: hide second notification in timelapse > remove mp4

- src/locales/pl.json
Just added more of bugfix polish translation
> locale(pl): fix polish translation

- src/locales/pl.json
Sorry for posting so many , I've already sent this to a polish discord server to search for bugs
> locale(pl): additional fix for polish language

- .github/workflows/code_style.yml
- .prettierignore
- cypress.json
- cypress/fixtures/example.json
- cypress/plugins/index.js
- package-lock.json
- package.json
- src/locales/de.json
- src/locales/en.json
- tsconfig.json
- vue-i18n-extract.config.js
This changes several things:
- Add a `.prettierignore` file to ignore specific files. So format all files by default.
- Improve the workflow so it can write annotations, but set it to have limited permissions. This due `pull_request_target` being used.
> style: improve prettier integration

- .github/workflows/update_changelog.yml
- CHANGELOG.md
- package.json
> build(changelog): ease down on the changelog updates, remove 'unreleased' part

- src/store/gui/remoteprinters/actions.ts
> fix: removing remote printer in remote mode

- src/components/settings/SettingsWebcamsTab.vue
* change input style for webcam settings to outlined
* add missing "dropdown indicator" for webcam icon menu
> refactor: rework webcam settings visuals

- src/components/inputs/MacroButton.vue
> fix: fix gcode from macros with single char attributes

- src/components/inputs/MiscellaneousSlider.vue
* also get rid of some redundant code
> fix: match input field behavior to slider behavior

- src/components/panels/Machine/ConfigFilesPanel.vue
- src/components/panels/MiscellaneousPanel.vue
- src/components/panels/ToolsPanel.vue
> fix: missing icon imports (follow up of #646)

- src/components/charts/TempChart.vue
> refactor: replace the mdiclock for an emoji on the TempChart

- src/store/gui/mutations.ts
> chore: remove unused mutations

- src/store/gui/getters.ts
> chore: remove unused getter

- src/components/TheSelectPrinterDialog.vue
- src/locales/en.json
> feat: change default port for https instances in remote mode

- src/components/mixins/base.ts
- src/components/panels/WebcamPanel.vue
- src/components/ui/Panel.vue
- src/components/ui/SubPanel.vue
- src/pages/Webcam.vue
- src/store/gui/actions.ts
- src/store/gui/getters.ts
- src/store/gui/index.ts
- src/store/gui/mutations.ts
- src/store/gui/types.ts
> feat: each viewport size can have different panels open/close

- src/components/charts/TempChart.vue
- src/store/printer/tempHistory/actions.ts
- src/store/printer/tempHistory/getters.ts
- src/store/server/mutations.ts
this setting should be in the moonraker data_store config block, but can also be in server config block as a fallback
> fix: search temperature_store_size in data_store and server

- .docker/nginx.conf
- .dockerignore
- .github/workflows/publish_docker.yml
- Dockerfile
- package-lock.json
This creates the `latest` version of the Docker image.
> build: add official Docker image

- src/components/panels/Machine/ConfigFilesPanel.vue
- src/components/settings/SettingsGeneralTab.vue
- src/locales/de.json
- src/locales/en.json
- estimate settings in interface setting
- "root" dropdown in config file panel
this PR fix #510 
> fix: add missing translation keys

- src/pages/Heightmap.vue
> fix: disable home button in heightmap page while printing

- src/components/TheEditor.vue
- src/plugins/helpers.ts
- src/store/editor/actions.ts
> feat: confirm before closing the browser tab

- src/store/server/actions.ts
> feat: display error messages when console is not on the screen

- src/components/announcements/AnnouncementMenuEntry.vue
- src/components/announcements/TheAnnouncementsMenu.vue
> chore: tweak visual appearance

- src/components/announcements/AnnouncementMenuEntry.vue
- src/components/announcements/TheAnnouncementsMenu.vue
> chore: more UI/UX tweaks

- src/pages/Dashboard.vue
> fix: compiler type warning

- src/components/charts/TempChart.vue
> fix: resize tempchart on window resize event

- src/locales/de.json
- src/locales/en.json
- src/locales/se-SV.json
for:
- german locales
- english locales
lint:
- swedish locales
> fix: update missing out of range translation

- src/components/TheEditor.vue
> feat: always show scrollbar in the editor

- src/components/settings/SettingsUiSettingsTab.vue
> refactor: remove unused option in SettingsUiSettingsTab.vue

- src/App.vue
- src/main.ts
> refactor: display scrollbar when mouse is moving

- src/components/webcams/Mjpegstreamer.vue
> fix: remove image from cache after loading it in Mjpegstreamer.vue

- src/components/webcams/Uv4lMjpeg.vue
> fix: close stream on beforeDestory Uv4lMjpeg.vue

- src/components/panels/GcodefilesPanel.vue
- src/components/panels/Status/Gcodefiles.vue
> refactor: match icon for editing config and gcode files

- src/components/TheEditor.vue
- src/store/editor/actions.ts
Signed-off-by: meteyou <meteyou@gmail.com>
> fix: edit files/gcodes in subfolders

- src/components/panels/ToolheadControls/CrossControl.vue
> fix(CrossControl): step size was not applied correctly

- package-lock.json
- package.json
- src/components/charts/HistoryAllPrintStatus.vue
- src/components/charts/HistoryFilamentUsage.vue
- src/components/charts/HistoryPrinttimeAvg.vue
- src/components/charts/TempChart.vue
- src/components/gcodeviewer/Viewer.vue
- src/components/panels/FarmPrinterPanel.vue
- src/components/panels/JobqueuePanel.vue
- src/components/panels/Status/Gcodefiles.vue
- src/components/panels/Status/Jobqueue.vue
- src/components/panels/Status/PrintstatusThumbnail.vue
- src/main.ts
> fix: resize issues with tempchart and other components

- src/components/webcams/Mjpegstreamer.vue
- src/components/webcams/MjpegstreamerAdaptive.vue
- src/components/webcams/Uv4lMjpeg.vue
> fix: stop stream when changing browser tab

- src/components/mixins/control.ts
- src/components/panels/ToolheadControls/CrossControl.vue
- src/components/panels/ToolheadControls/MoveToControl.vue
> fix: fix some issues with unreadable values in the control panel

- src/components/inputs/TemperatureInput.vue
> fix: unable to set heater target temperature

- src/components/panels/GcodefilesPanel.vue
- src/store/files/actions.ts
> fix: add file from sub directory to job queue

- src/components/panels/FarmPrinterPanel.vue
> fix: add u4vl-mjpeg to printfarm & only display supported modes

- src/components/mixins/webcam.ts
- src/components/panels/FarmPrinterPanel.vue
- src/components/panels/WebcamPanel.vue
- src/components/settings/SettingsWebcamsTab.vue
> fix: store only name of icon instead of svg in moonraker db

- src/locales/ru.json
Correct translation as suggested in #835 
> locale(ru): update Russian locale

- src/store/printer/tempHistory/getters.ts
> refactor: remove temperature_store_size from server section

- src/locales/fr.json
Thx Ronald Forster for updating this locale file
> locale(fr): update French localization

- src/components/panels/GcodefilesPanel.vue
> fix: search files also with single word snippets

- src/locales/ja.json
- Follow-up on changes to en.jason
- Correcting mistranslations
> locale(ja): update Japanese localization

- src/components/settings/SettingsConsoleTab.vue
- src/locales/de.json
- src/locales/en.json
> fix: add headlines to console tab settings

- src/components/webcams/Mjpegstreamer.vue
- src/components/webcams/MjpegstreamerAdaptive.vue
- src/components/webcams/Uv4lMjpeg.vue
> fix: don't start webcam after switching tab

- src/locales/en.json
> locale(en): fix typo in GreaterOrEqualError

- src/components/charts/HistoryAllPrintStatus.vue
- src/components/charts/HistoryFilamentUsage.vue
- src/components/charts/HistoryPrinttimeAvg.vue
- src/components/charts/TempChart.vue
- src/pages/Heightmap.vue
> fix: echarts getters in heightmap, tempchart & history statistics

- src/components/webcams/Mjpegstreamer.vue
- src/components/webcams/Uv4lMjpeg.vue
> fix: fix img size without a stream (u4vl-mode)

- src/components/webcams/MjpegstreamerAdaptive.vue
> fix: MjpegstreamerAdaptive.vue image size

- src/store/server/getters.ts
> fix: max size of tempchart

- src/store/printer/getters.ts
> fix: sort of toolchange macros

- src/components/gcodeviewer/Viewer.vue
> fix: display filename in gcodeviewer

- src/components/inputs/MiscellaneousSlider.vue
- src/components/inputs/ToolSlider.vue
fixes a similar bug as in https://github.com/mainsail-crew/mainsail/issues/827
> fix: unable to set target values

- src/components/inputs/MoveToInput.vue
- src/components/panels/ToolheadControls/MoveToControl.vue
similar bug as in https://github.com/mainsail-crew/mainsail/issues/827
> fix: unable to submit coordinate values

- src/components/CommandHelpModal.vue
> fix: CommandHelpModal mobile fullscreen size

- src/locales/pl.json
Thx to Furrciak for the translation!
> locale(pl): update Polish locale

- package.json
> chore: exclude .DS_Store files in build.zip

- .github/ISSUE_TEMPLATE/bug_report.yml
requires the user to provide the mainsail version
> chore(bug_report.yml): extend issue template

- .github/workflows/issues-no-response.yml
> chore: add workflow to close issues with 'User Input' label after 7days

- .github/workflows/check_locale.yml
- package-lock.json
- package.json
- vue-i18n-extract.config.js
This PR adds a workflow which checks every pull_request with locale files with i18n-extract and writes a comment in the PR with the results.
> chore: add workflow to check locale files in pull requests

- src/store/printer/tempHistory/actions.ts
- src/store/printer/tempHistory/getters.ts
> fix: fix typo in adding new heaters/temperature_fans to chart dataset

- src/components/panels/GcodefilesPanel.vue
> fix: add fallback for gcode files without thumbnail

- src/store/printer/getters.ts
> fix: match mcu temp sensor of additional mcus

- src/locales/hu.json
Updated as the en.json is today
> locale(hu): update Hungarian localization

- src/components/panels/HistoryListPanel.vue
> fix: fix output with number groupings & add slicer in csv header

- src/store/gui/actions.ts
> fix: reset webcam store on printer switch

- .github/workflows/auto-analyze.yml
> chore: add auto-analyze.yml action

- public/config.json
- src/locales/de.json
- src/main.ts
> feat: add defaultLocale in config.json

- src/locales/de.json
> locale(de): update German localization

- src/components/settings/SettingsGeneralTab.vue
- src/locales/de.json
- src/locales/en.json
- src/store/farm/printer/getters.ts
- src/store/gui/index.ts
- src/store/gui/types.ts
- src/store/printer/getters.ts
> feat: add option to switch print progress calculation

- src/components/settings/SettingsGeneralTab.vue
- src/locales/de.json
- src/locales/en.json
> fix: add missing locale to factory reset options

- .github/workflows/auto-analyze.yml
> chore: add github_token to auto-analyze.yml

- .github/workflows/auto-analyze.yml
> chore: fix issues with auto analyze workflow

- src/components/panels/Machine/SystemPanelHost.vue
> fix: fix type issue in releaseName parsing

- src/components/settings/SettingsWebcamsTab.vue
- src/locales/de.json
- src/locales/en.json
> feat: add button to edit crowsnest.conf in webcam settings

- src/components/panels/Timelapse/TimelapseFilesPanel.vue
- src/locales/de.json
- src/locales/en.json
- src/store/gui/index.ts
- src/store/gui/types.ts
> feat: add multiselect to timelapse file manager

- src/store/printer/getters.ts
> fix: fix progress above 100% with filament based calculation

- src/components/panels/ExtruderControlPanel.vue
- src/locales/de.json
- src/locales/en.json
> feat: show nozzle size in estimated extrusion info

- src/components/panels/HistoryListPanel.vue
> feat: export only selected jobs from print history

- src/components/panels/ExtruderSettings/PressureAdvanceSettings.vue
> fix: use correct unit for pressure advance

- package-lock.json
- package.json
- src/components/charts/HistoryAllPrintStatus.vue
- src/components/charts/TempChart.vue
> fix: fix dep loading issue after update vite

- src/components/panels/Status/Gcodefiles.vue
- src/components/panels/Status/Jobqueue.vue
> fix: remove scrollbar on init load of status panel

- package-lock.json
- package.json
> chore: push version number to v2.3.0-beta1

- .github/workflows/stale.yml
> chore: change cron interval stale action

- src/locales/fr.json
> locale(fr): update fr locale

- CONTRIBUTING.md
Signed-off-by: Dominik Willner th33xitus@gmail.com
> chore: update broken link to DCO

- src/store/gui/remoteprinters/actions.ts
> fix: load instances from localStore if instance store is browser

- src/components/inputs/Codemirror.vue
This PR will fix [FR] #1082
Signed-off-by: Kevin Lemarchand <lem.kev@gmail.com>
> refactor: extend css editor support to .scss and .sass files

- src/locales/es.json
- src/locales/fr.json
- src/locales/nl.json
- src/locales/ru.json
> chore: lint:fix locales

- src/components/TheSidebar.vue
- src/components/dialogs/AboutDialog.vue
- src/components/modals/AboutModal.vue
> chore: rename and clean up AboutModal

- src/components/dialogs/TheManualProbeDialog.vue
> fix: set init values in TheManualProbeDialog.vue

- src/components/panels/Machine/SystemPanelHost.vue
- src/store/server/getters.ts
> refactor: display bit version of OS

- src/components/settings/SettingsGeneralTab.vue
- tsconfig.json
> chore(build): update compiler target to support import.meta

- src/components/panels/TemperaturePanel.vue
- src/store/printer/getters.ts
- src/store/printer/types.ts
fixes #1105 
thx @alchemyEngine for this Klipper feature!
> feat: add z_thermal_adjust to temperatures panel

- package-lock.json
- package.json
> chore: update gcode viewer to V3.1.4

- src/components/mixins/base.ts
- src/components/webcams/Mjpegstreamer.vue
- src/components/webcams/MjpegstreamerAdaptive.vue
- src/components/webcams/Uv4lMjpeg.vue
> fix: fix relative webcam urls with port

- src/components/TheTopbar.vue
- src/components/mixins/base.ts
- src/components/panels/GcodefilesPanel.vue
- src/store/variables.ts
Identify iOS and allow the upload of all file types.
fix #1117 
> fix: cannot upload GCODE files on iOS

- src/components/inputs/MacroButton.vue
> feat: multi column for many inputs in gcode macro

- src/components/panels/ExtruderControlPanel.vue
> fix(ExtruderPanel): wrong calculation for estimated extrusion length

- src/store/printer/getters.ts
> fix: display layer count with older klipper versions

- src/components/panels/Machine/SystemPanelHost.vue
- src/store/server/getters.ts
> fix: display can interfaces in system panel

- src/components/webcams/Mjpegstreamer.vue
- src/components/webcams/MjpegstreamerAdaptive.vue
- src/components/webcams/Uv4lMjpeg.vue
> fix: fix relative webcam urls on multi instances

- src/components/inputs/NumberInput.vue
> fix: fix handling issues with number-inputs

- src/store/printer/getters.ts
> fix: fix neopixel settings if name is uppercase

- README.md
> docs: add BIGTREETECH to repo README as official sponsor

- src/locales/da.json
- src/locales/de.json
- src/locales/en.json
- src/locales/ja.json
- src/locales/nl.json
- src/locales/tr.json
- src/locales/zh.json
Ran formatting so other languages had their json re-ordered correctly too.
> locale(nl): Update NL localization

- .github/workflows/release.yml
- cliff-release.toml
- cliff.toml
> chore: fix release workflow

- src/components/panels/Timelapse/TimelapseStatusPanel.vue
> fix: add webcam rotate to timelapse preview

- src/components/panels/Status/ExcludeObjectDialogMap.vue
> fix: fix ExcludeObjectDialogMap for delta printers

- src/components/gcodeviewer/CodeStream.vue
- src/components/gcodeviewer/Viewer.vue
Fix updateForceWireMode call when CNC mode is toggled. Fix overflow on codestream control
> fix: G-Code Viewer UI fixes

- src/components/panels/HistoryListPanel.vue
> fix: fix dateTime output in print history detail dialog

- src/store/gui/getters.ts
> fix: hide unused panels on dashboard

- src/store/files/actions.ts
- src/store/variables.ts
> feat: hide/ignore .git directories in file init process

- src/components/panels/Machine/LogfilesPanel.vue
- src/locales/en.json
- src/store/files/actions.ts
- src/store/variables.ts
> feat: log rollover function for klipper and moonraker

- src/components/panels/GcodefilesPanel.vue
- src/components/panels/Machine/ConfigFilesPanel.vue
- src/components/panels/Timelapse/TimelapseFilesPanel.vue
> refactor: rename download zip name

- src/components/panels/Machine/LogfilesPanel.vue
> fix: fix cancel button in rollover logs dialog

- src/locales/de.json
- src/locales/en.json
- src/locales/ja.json
> locale: remove unused locale `PresetSubTitle`

- src/components/mixins/base.ts
- src/components/panels/KlippyStatePanel.vue
- src/locales/de.json
- src/locales/en.json
> fix: fix output of klippy state, if UDS path/address dont fit

- src/App.vue
- src/components/dialogs/TheScrewsTiltAdjustDialog.vue
- src/components/dialogs/TheScrewsTiltAdjustDialogEntry.vue
- src/locales/en.json
- src/store/printer/actions.ts
- src/store/printer/mutations.ts
- src/store/variables.ts
> feat: add helper display for screws_tilt_adjust

- src/components/panels/Status/PauseAtLayerDialog.vue
- src/components/panels/StatusPanel.vue
- src/locales/de.json
- src/locales/en.json
> feat: add function to send PAUSE at a specific layer change

- src/components/settings/SettingsTimelapseTab.vue
this PR is related to this FR: https://github.com/mainsail-crew/moonraker-timelapse/issues/74
> feat: add x_only and y_only option in timelapse park position 

- src/components/webcams/Mjpegstreamer.vue
- src/components/webcams/MjpegstreamerAdaptive.vue
> fix: fix position of webcam fps

- src/App.vue
- src/locales/de.json
- src/locales/en.json
- src/store/getters.ts
> fix: fix browser title, when printer is off

- src/components/panels/StatusPanel.vue
> fix: only display PAUSE AT LAYER button, when the macros exists

- src/components/inputs/MiscellaneousSlider.vue
- src/components/settings/SettingsUiSettingsTab.vue
- src/locales/de.json
- src/locales/en.json
- src/store/gui/index.ts
- src/store/gui/types.ts
- src/store/printer/getters.ts
This PR will save performance in the browser.
fixes #1229.
> feat: allow fan animations to be disabled to save browser perf.

- src/locales/en.json
- src/pages/Heightmap.vue
> fix: disallow non-ascii chars in bed_mesh name

- src/components/panels/ExtruderControlPanel.vue
> fix: find LOAD & UNLOAD_FILAMENT macros case-insensitive

- src/components/inputs/MiscellaneousSlider.vue
> fix: fix miscellaneous slider + button for fans/outputs with max power

- src/components/panels/Status/PrintstatusPrinting.vue
- src/store/printer/getters.ts
This PR allows and displays a negative time in the slicer estimate when it's overrun - useful for dialing in slicer estimation and getting a clear picture of how much it went over.
#1315 
No post-deployment tasks.
> feat: Allow negative time estimate in slicer

- src/components/panels/GcodefilesPanel.vue
- src/components/panels/Machine/ConfigFilesPanel.vue
- src/locales/en.json
> feat: add function to duplicate gcode files

- src/components/settings/SettingsUiSettingsTab.vue
This PR fixes a bug I noticed in where the getter for disableFanAnimation was fetching the wrong value.
https://github.com/mainsail-crew/mainsail/pull/1371
> fix: disableFanAnimation getter getting wrong value

- src/components/settings/SettingsNavigationTabItem.vue
This PR fix only a eslint issue in the SettingsNavigationTabItem.vue file.
> style: fix eslint issue in SettingsNavigationTabItem

- src/pages/Heightmap.vue
This PR adds  the bed aspect ratio to the heightmap graph.
This is espacially usefull for highly non square print beads (mine is 600 x 300), see Screenshots below.
None
<td valign="center"> <img src="https://github.com/mainsail-crew/mainsail/assets/8619525/b9765cf3-086f-42d3-9694-afbe30350b53" width="450"></td>
<td valign="center"> <img src="https://github.com/mainsail-crew/mainsail/assets/8619525/0d3024b3-5dd0-4095-ae12-9fe3b3179d60" width="450"></td>
No
Signed-off-by: Michael Jäger michael@mjaeger.eu
> feat: add bed aspect ratio to heightmap graph

- src/locales/en.json
This PR remove one unused key in locale/en.json
none
none
> locale(en): remove unused key

- src/components/ui/Panel.vue
This PR fix type issues with the panel title prop and refactor the code style of Panel.vue.
none
none
> refactor: refactor Panel.vue

- .github/workflows/release.yml
This PR fixes the release workflow
none
none
> chore: update ftp upload action in release workflow

- src/store/printer/getters.ts
This PR will fix an issue with AM/PM switch at 12 PM in the StatusPanel ETA time
fixes #1461 
none
> fix: fix issue with ETA and 12h time format

- src/locales/pl.json
Automatic PR from my self-hosted Weblate
> locale(pl): Update Polish translation

- src/components/settings/Presets/PresetsEntry.vue
- src/components/settings/Presets/PresetsEntryCooldown.vue
- src/components/settings/Presets/PresetsForm.vue
- src/components/settings/Presets/PresetsFormCooldown.vue
- src/components/settings/SettingsPresetsTab.vue
This PR is to fix an error in the SettingsPresetTab. I also refactored the complete settings tab.
fixes #1498 
none
none
> fix: fix issue with create/edit presets and refactor SettingsPresetsTab

- src/components/panels/Temperature/TemperaturePanelListItem.vue
This pr fixes the cursor style on TemperaturePanelItems names. Which is supposed to be a pointer and not just the default cursor.
> fix: fix cursor style for item name to be a pointer

- src/store/gui/presets/getters.ts
- src/store/gui/presets/mutations.ts
- update preset overwrite all entries
- sort all preset temps in the dropdown
fixes #1525 
none
none
> fix: fix some issues with the presets

- src/locales/pl.json
> locale(pl): Update Polish translations

- src/components/panels/Extruder/ExtruderControlPanelTools.vue
- src/components/panels/Extruder/ExtruderControlPanelToolsItem.vue
Improve the tool color selector in the extruder panel. Thx to @HelgeKeck for this nice idea!
fixes: #1272
> refactor: rework tool color in extruder panel

- src/components/panels/GcodefilesPanel.vue
- src/components/panels/Machine/ConfigFilesPanel.vue
- src/components/panels/Machine/UpdatePanel/GitCommitsList.vue
- src/components/panels/Timelapse/TimelapseFilesPanel.vue
This PR fix the wrong getDate/getDay function in multiple files.
none
none
none
> fix: fix wrong date function in multiple files

- src/locales/en.json
This PR only remove unused keys in the english locale file.
none
none
> locale(en): remove unused keys in english locale

- src/components/panels/Timelapse/TimelapseStatusPanel.vue
This PR fix the horizontal & vertical flip function from webcams in the timelapse preview.
none
none
> fix: fix webcam flip in timelapse preview

- src/components/panels/WebcamPanel.vue
This PR fix the condition for the cam switch in the webcam page.
> fix: fix webcam switch button

- src/locales/fr.json
> locale(fr):correction of several errors

- src/locales/fr.json
> locale(fr):Correction of the term Unretract

- src/sw.ts
This PR just disable the workbox dev logs in the browser console.
none
none
none
> chore: disable workbox logs

- .github/workflows/check_locale.yml
Update check_locale.yml to new Github-Worflow output method.
- docs: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- Test in my private repo: https://github.com/meteyou/mainsail-dev/pull/9
> chore: update check_locale.yml to new github workflow output

- src/store/gui/getters.ts
This PR fix the 12-hour browser time format detection for the auto mode. Thx to Aubey for the hint!
Discord: https://discord.com/channels/758059413700345988/1174115244671504455/1175832933974691952
none
none
> fix: fix 12hour browser time format detection

- src/locales/fr.json
> locale(fr): Add translation clean_nozzle and purge_filament

- src/components/panels/ToolheadControlPanel.vue
- src/components/panels/ToolheadControls/MoveToControl.vue
- src/components/panels/ToolheadControls/ToolheadPanelSettings.vue
- src/locales/en.json
- src/store/gui/index.ts
- src/store/gui/types.ts
This  PR add options to hide parts of the ToolheadPanel.
fixes the first part of #1619
> feat: add option to hide parts of the ToolheadPanel

- src/locales/fr.json
> locale(fr): Add HeightMapTab and others updates

- src/components/inputs/MiscellaneousLight.vue
This PR should fix an issue with hidden light groups.
none
none
none
> fix: fix issue with hidden LED groups

- src/pages/Heightmap.vue
This PR only change the height of the heightmap.
none
before:
after:
none
> feat: resize heightmap to get a better heightmap overview

- src/components/panels/Machine/LogfilesPanel.vue
- src/components/panels/Machine/LogfilesPanel/LogfilesPanelGenericLog.vue
- src/components/panels/Machine/LogfilesPanel/LogfilesPanelRolloverDialog.vue
- src/store/variables.ts
This PR adds the mmu.log file to the Logfiles panel if it exists and refactor the complete panel.
none
none
none
> feat: add mmu.log to logfiles panel

- src/components/dialogs/SpoolmanChangeSpoolDialogRow.vue
This PR fix the Spoolman list (location & comment).
none
after:
none
> fix: fix spoolman list (comment & location)

- src/components/charts/TempChart.vue
This PR fix a code issue in the Tempchart with the theme reader.
none
none
none
> fix: fix theme issue in tempchart

- src/components/mixins/base.ts
- src/components/mixins/webcam.ts
This PR change the hardcoded Moonraker ports to automatic read ports from the Moonraker config.
maybe fixes #1710 but without any config, I don't know if this is the issue...
none
none
> fix: fix webcam url with multiple moonraker instances

- src/components/panels/HistoryListPanel.vue
This PR fixes the icon of the history entry for deleted files.
none
none
none
> fix: fix icon for deleted files in the history

- src/components/charts/TempChart.vue
This PR will change to setOption in the tempchart and will stop the chart update, until the mouse if hovered.
fixes #1655 
none
none
> fix: fix tooltip of tempchart

- .github/label-actions.yml
This PR just fix a typo in the issue tracker bot text.
none
none
none
> chore: fix typo in bot text

- package-lock.json
- package.json
Update @sindarius/gcodeviewer dependency to latest so it works also with gcode files generated by OrcaSlicer
Closes #1752 
No changes on frontend, just allows using the gcode viewer also with files from OrcaSlicer
> chore(deps): Update @sindarius/gcodeviewer

- src/store/server/spoolman/actions.ts
This PR adds the support of the V2 response from Moonraker.
PR for the V2 response in Moonraker: https://github.com/Arksine/moonraker/pull/792
none
none
> refactor: refactor spoolman integration to support v2 response

- .github/workflows/auto-analyze.yml
- .github/workflows/build.yml
- .github/workflows/check-pr-title.yml
- .github/workflows/code_style.yml
- .github/workflows/test.yml
This PR updates only some actions in the workflow files to fix node16 deprecated warnings.
none
none
none
> ci: update workflow actions

- src/locales/en.json
Fix typo in EN locale
fixes #1775 
none
none
> locale(en): fix typo in DescriptionPreviouslyThrottled

- src/components/console/ConsoleTableEntry.vue
This PR fix long lines in the console. You can see it in the screenshots.
none
before:
after:
none
> fix: fix long content lines in console

- .github/PULL_REQUEST_TEMPLATE.md
This PR fixes a typo and rewords some parts of the pull request template
None
None
> chore: fix typo/reword some parts of the pull request template

- src/store/gui/maintenance/getters.ts
This PR fix the validation from the overdue maintenance entries for printtime based entries.
> fix(maintenance): fix overdue check from printtime based entries

- src/components/TheConnectingDialog.vue
This PR update the path to moonraker.log in TheConnectingDialog.
none
none
none
> fix: update moonraker log path in TheConnectingDialog.vue

- src/store/printer/actions.ts
- src/store/server/getters.ts
This PR add the output from the app in the system loads panel. This will help to identify a Danger-Klipper instance for example.
PR in DK: https://github.com/DangerKlippers/danger-klipper/pull/285
none
> feat(systemLoads): add function to output app name in system loads panel

- package-lock.json
- package.json
This PR update the gcodeviewer to fix rendering issues with high/max quality.
fixes: #1924 
none
none
> fix(gcodeviewer): update gcodeviewer to fix rendering issues

- src/components/TheTopbar.vue
This PR remove a unused getter and fix the upload snackbar.
none
none
none
> refactor: refactor TheTopbar, remove unused gette, fix snackbar

- public/img/themes/sidebarLogo-ldo.svg
- src/store/variables.ts
This PR adds a LDO Motion theme.
none
none
> feat(theme): add LDO Motion theme

- src/components/console/CommandHelpModal.vue
- src/components/console/CommandHelpModalEntry.vue
- src/components/console/ConsoleTable.vue
- src/components/inputs/ConsoleTextarea.vue
- src/components/mixins/console.ts
- src/components/panels/MiniconsolePanel.vue
- src/locales/en.json
- src/pages/Console.vue
- src/plugins/webSocketClient.ts
- src/store/printer/actions.ts
- src/store/printer/mutations.ts
- src/store/printer/types.ts
- src/store/server/actions.ts
This PR change from the Moonraker helplist function to the Printer.Gcode for live updates in the Gcode list.
none
none
none
> feat(Console): Change from Helplist to Printer.Gcode

- src/components/panels/Status/Gcodefiles.vue
- src/components/panels/Status/GcodefilesEntry.vue
This PR just refactor the files list in the StatusPanel on the Dashboard. It split the entry from the list.
none
none
none
> refactor: refactor files list in StatusPanel

- src/store/variables.ts
This PR adds the SGP40 Sensor to additionalSensors to display GAS and VOC in the temperature panel
none
none
none
> feat: add SGP40 support

- package-lock.json
- package.json
- src/components/gcodeviewer/Viewer.vue
This PR just refactor the gcodeviewer and make some function more error proof and update the gcodeviewer lib. This will not add any new function.
fixes #2024
> refactor: refactor gcodeviewer page

- src/locales/zh.json
> locale(zh): update chinese locale

- src/components/TheEditor.vue
- src/components/mixins/base.ts
- src/store/types.ts
- src/store/variables.ts
This PR fix the docs link in the Editor topbar and in the sidebar for Kalico.
none
none
none
> fix(Editor): fix docs link for Kalico

- src/components/TheEditor.vue
This PR fix the structure sidebar for files without a section, but values/attributes in it.
none
none
none
> fix(Editor): fix sidebar for files with values without a section

- package-lock.json
- package.json
This PR update the gcodeviewer to v3.7.17.
none
none
none
> chore: update gcodeviewer to v3.7.16

- .github/workflows/auto-analyze.yml
- .github/workflows/check_locale.yml
This PR fixes some security issues from the tj-actions/changed-files action.
fixes CVE-2025-30066
none
none
> ci: update tj-actions/changed-files action in workflows

- src/store/printer/types.ts
There are two identical definitions of the PrinterStateLight interface one after the other. This removes one of them.
> refactor: Remove duplicate PrinterStateLight definition

- src/store/editor/actions.ts
- src/store/editor/index.ts
- src/store/editor/types.ts
This PR fixes the up- & download speed rate in the snackbar while uploading or downloading files.
none
none
none
> fix: fix the axios up- & download rate

- src/components/panels/Machine/UpdatePanel.vue
- src/components/panels/Machine/UpdatePanel/Entry.vue
- src/components/panels/Machine/UpdatePanel/UpdateHintAll.vue
This pr fixes the bug where python packages using prelease versions are shown as UNKNOWN / invalid version.
E.g. `0.0.2a3` is invalid in strict semver.
None
> fix(python): loose package versions

- src/components/panels/Machine/UpdatePanel/Entry.vue
Only git repos can be corrupt and thus soft recover. Disable it for others, the button simply does nothing.
> fix: only git repos can soft recover

- package-lock.json
- package.json
This PR just updates some npm deps
none
none
none
> build(deps): update dependencies in package.json

- .github/workflows/check_locale.yml
This PR fix the glob issue with the check-locale workflow.
none
none
none
> ci(check-locale): fix check-locale workflow

- src/components/mixins/historyStats.ts
This PR just remove an unused import in the historyStats.ts mixin.
none
none
none
> refactor: remove unused vue import in historyStats.ts
